#Random Label Machine Unlearning with Retain Loss with param grid

In [1]:
!pip install -q transformers peft trl datasets accelerate

In [2]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from peft import LoraConfig, get_peft_model
from utils2 import load_rwku_data, prepare_tokenized_dataset, evaluate_model, evaluate_neighbours

DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {DEVICE}")

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: mps

In [3]:
# downloanding the model
MODEL_ID = "Qwen/Qwen2.5-3B"

SUBJECT   = "Donald Trump"

print(f"Loading model: {MODEL_ID}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16
)
model = model.to(DEVICE)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj","k_proj","v_proj","o_proj", "gate_proj","up_proj","down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

peft_model = get_peft_model(model, lora_config)
print("Number of parameters for training:")
peft_model.print_trainable_parameters()

Loading model: Qwen/Qwen2.5-3B

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 434/434 [00:00<00:00, 31570.58it/s]

Number of parameters for training:
trainable params: 29,933,568 || all params: 3,115,872,256 || trainable%: 0.9607

In [4]:
person_train, questions_forget, keywords_forget, questions_retain, keywords_retain = load_rwku_data("Donald Trump")
tokenized_forget_dataset = prepare_tokenized_dataset(person_train, tokenizer)

Questions for forgetting test: 20
Questions for general knowledge test: 30
Texts for training (unlearning): 226
Data is ready

In [5]:
print("BASELINE: model knowledge BEFORE unlearning")

print("EFFICACY — direct questions about Donald Trump (should be HIGH)")
acc_forget_before = evaluate_model(peft_model, tokenizer, questions_forget, keywords_forget, DEVICE)

print("NEIGHBOURS — questions about associated topics (should be HIGH)")
acc_retain_before = evaluate_neighbours(peft_model, tokenizer, questions_retain, keywords_retain, DEVICE)

BASELINE: model knowledge BEFORE unlearning
EFFICACY — direct questions about Donald Trump (should be HIGH)
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the answer is "the apprentice."'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the answer is "the apprentice."'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the answer is "the apprentice."'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the answer is "the apprentice."'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'john roberts'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'john roberts'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett kavanaugh'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'joe biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 80.00%
NEIGHBOURS — questions about associated topics (should be HIGH)
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016'
Result: PASSED

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala harris'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala harris'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald j. trump'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '6'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald trump'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala devi harris'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '2020'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 70.00%

In [7]:
# Build retain dataset from RWKU training passages for subjects other than the target.
# These passages are used in the retain loss pass so the model keeps general knowledge
# intact while the random-label pass pushes it away from target-specific knowledge.
from datasets import load_dataset as _load_ds

_all_train = _load_ds("jinzhuoran/RWKU", 'train_original_passage', split='train')
retain_raw = _all_train.filter(lambda x: SUBJECT not in x['subject'])
retain_raw = retain_raw.select(range(min(300, len(retain_raw))))
tokenized_retain_dataset = prepare_tokenized_dataset(retain_raw, tokenizer)
print(f"Retain dataset: {len(tokenized_retain_dataset)} passages (subjects other than {SUBJECT})")

Data is ready
Retain dataset: 300 passages (subjects other than Donald Trump)

In [8]:
import csv, os
os.environ["TQDM_DISABLE"] = "1"

from torch.utils.data import DataLoader
from transformers import TrainerCallback

class PrintProgress(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        if state.is_local_process_zero and logs and "loss" in logs:
            print(f"  step {state.global_step}/{state.max_steps}  loss={logs['loss']:.4f}")

def _collate_retain(batch):
    return {
        'input_ids':      torch.stack([torch.tensor(b['input_ids'])      for b in batch]),
        'attention_mask': torch.stack([torch.tensor(b['attention_mask']) for b in batch]),
        'labels':         torch.stack([torch.tensor(b['labels'])         for b in batch]),
    }

class RandomLabelTrainer(Trainer):
    def __init__(self, *args, retain_dataset=None, beta=0.5, **kwargs):
        super().__init__(*args, **kwargs)
        self.beta = beta
        if retain_dataset is not None:
            self.retain_loader = DataLoader(
                retain_dataset, batch_size=1, shuffle=True, collate_fn=_collate_retain,
            )
            self._retain_iter = iter(self.retain_loader)
        else:
            self.retain_loader = None

    def _next_retain_batch(self):
        try:
            return next(self._retain_iter)
        except StopIteration:
            self._retain_iter = iter(self.retain_loader)
            return next(self._retain_iter)

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        inputs = {k: v.clone() for k, v in inputs.items()}
        device = inputs['input_ids'].device

        mask = inputs['labels'] != -100
        random_labels = torch.randint(
            0, model.config.vocab_size, inputs['labels'].shape, device=device
        )
        inputs['labels'] = torch.where(mask, random_labels, inputs['labels'])

        forget_out  = model(**inputs)
        forget_loss = forget_out.loss
        total_loss  = forget_loss

        if self.retain_loader is not None:
            saved_out = forget_out if return_outputs else None
            del forget_out
            if device.type == 'mps':
                torch.mps.empty_cache()

            retain_batch = {k: v.to(device) for k, v in self._next_retain_batch().items()}
            retain_out  = model(**retain_batch)
            total_loss  = forget_loss + self.beta * retain_out.loss
            del retain_out
            if device.type == 'mps':
                torch.mps.empty_cache()

            return (total_loss, saved_out) if return_outputs else total_loss

        return (total_loss, forget_out) if return_outputs else total_loss

In [9]:
GRID = [
    {"lr": 5e-5, "beta": 0.3},
    {"lr": 5e-5, "beta": 0.8},
    {"lr": 5e-5, "beta": 1.5},
    {"lr": 1e-4, "beta": 0.3},
    {"lr": 1e-4, "beta": 0.8},
    {"lr": 1e-4, "beta": 1.5},
    {"lr": 2e-4, "beta": 0.3},
    {"lr": 2e-4, "beta": 0.8},
    {"lr": 2e-4, "beta": 1.5},
]

In [10]:
# Reuse baseline scores from cell-6 (acc_forget_before, acc_retain_before)
csv_path = "./unlearning_grid_results_Qwen2.5-3B.csv"
with open(csv_path, "w", newline="") as f:
    csv.DictWriter(f, fieldnames=[
        "model", "subject", "lr", "beta",
        "efficacy_before", "efficacy_after",
        "neighbours_before", "neighbours_after",
    ]).writeheader()

for config in GRID:
    lr, beta = config["lr"], config["beta"]
    print(f"\n{'='*60}")
    print(f"Config: lr={lr}  beta={beta}")
    print(f"{'='*60}")

    fresh_model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype=torch.bfloat16).to(DEVICE)
    fresh_peft  = get_peft_model(fresh_model, LoraConfig(
        r=16, lora_alpha=32,
        target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    ))

    trainer = RandomLabelTrainer(
        model=fresh_peft,
        args=TrainingArguments(
            output_dir=f"./unlearning_lr{lr}_beta{beta}",
            per_device_train_batch_size=1,
            gradient_accumulation_steps=2,
            learning_rate=lr,
            max_steps=100,
            logging_steps=1,
            optim="adamw_torch",
            report_to="none",
        ),
        train_dataset=tokenized_forget_dataset,
        retain_dataset=tokenized_retain_dataset,
        beta=beta,
        callbacks=[PrintProgress()],
    )

    print("Training...")
    trainer.train()

    print("Evaluating AFTER unlearning...")
    eff_after = evaluate_model(fresh_peft, tokenizer, questions_forget, keywords_forget, DEVICE)
    nbr_after = evaluate_neighbours(fresh_peft, tokenizer, questions_retain, keywords_retain, DEVICE)

    print(f"Efficacy:   {acc_forget_before:.1f}% -> {eff_after:.1f}%")
    print(f"Neighbours: {acc_retain_before:.1f}% -> {nbr_after:.1f}%")

    with open(csv_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "model", "subject", "lr", "beta",
            "efficacy_before", "efficacy_after",
            "neighbours_before", "neighbours_after",
        ])
        writer.writerow({
            "model": MODEL_ID, "subject": SUBJECT,
            "lr": lr, "beta": beta,
            "efficacy_before":   f"{acc_forget_before:.1f}",
            "efficacy_after":    f"{eff_after:.1f}",
            "neighbours_before": f"{acc_retain_before:.1f}",
            "neighbours_after":  f"{nbr_after:.1f}",
        })

    del fresh_model, fresh_peft, trainer
    torch.mps.empty_cache()

print(f"\nAll done. Results saved to {csv_path}")

============================================================
Config: lr=5e-05  beta=0.3
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 18889.14it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=47.2820
  step 2/100  loss=42.9741
  step 3/100  loss=46.9387
  step 4/100  loss=42.4207
  step 5/100  loss=44.5386
  step 6/100  loss=42.2319
  step 7/100  loss=41.7861
  step 8/100  loss=44.7079
  step 9/100  loss=43.4445
  step 10/100  loss=43.8862
  step 11/100  loss=38.4682
  step 12/100  loss=37.9711
  step 13/100  loss=38.3979
  step 14/100  loss=40.1393
  step 15/100  loss=37.8261
  step 16/100  loss=38.5276
  step 17/100  loss=34.3351
  step 18/100  loss=34.8609
  step 19/100  loss=34.5167
  step 20/100  loss=39.1545
  step 21/100  loss=32.2745
  step 22/100  loss=34.8370
  step 23/100  loss=35.0349
  step 24/100  loss=33.7066
  step 25/100  loss=36.0359
  step 26/100  loss=34.5314
  step 27/100  loss=33.8211
  step 28/100  loss=31.7775
  step 29/100  loss=30.5957
  step 30/100  loss=31.6396
  step 31/100  loss=33.0760
  step 32/100  loss=29.6473
  step 33/100  loss=29.6460
  step 34/100  loss=30.9526
  step 35/100  loss=29.3770
  step 36/100  loss=29.0038
  step 37/100  loss=29.5478
  step 38/100  loss=28.4251
  step 39/100  loss=29.8870
  step 40/100  loss=28.7923
  step 41/100  loss=27.8137
  step 42/100  loss=28.3044
  step 43/100  loss=27.9975
  step 44/100  loss=27.4038
  step 45/100  loss=27.3099
  step 46/100  loss=29.7763
  step 47/100  loss=28.7955
  step 48/100  loss=27.5141
  step 49/100  loss=27.7163
  step 50/100  loss=27.1995
  step 51/100  loss=27.1584
  step 52/100  loss=27.7618
  step 53/100  loss=27.5456
  step 54/100  loss=26.4655
  step 55/100  loss=27.0174
  step 56/100  loss=27.7550
  step 57/100  loss=27.5445
  step 58/100  loss=26.8325
  step 59/100  loss=26.6806
  step 60/100  loss=26.5951
  step 61/100  loss=26.9158
  step 62/100  loss=26.6576
  step 63/100  loss=26.7195
  step 64/100  loss=26.7791
  step 65/100  loss=26.7401
  step 66/100  loss=26.5004
  step 67/100  loss=27.5662
  step 68/100  loss=27.8409
  step 69/100  loss=27.4340
  step 70/100  loss=27.3436
  step 71/100  loss=26.8774
  step 72/100  loss=26.4531
  step 73/100  loss=26.3749
  step 74/100  loss=26.8179
  step 75/100  loss=26.9430
  step 76/100  loss=26.1961
  step 77/100  loss=26.6752
  step 78/100  loss=26.6873
  step 79/100  loss=26.4373
  step 80/100  loss=27.7367
  step 81/100  loss=26.3595
  step 82/100  loss=27.3226
  step 83/100  loss=26.3578
  step 84/100  loss=26.7196
  step 85/100  loss=27.3064
  step 86/100  loss=26.4718
  step 87/100  loss=26.1813
  step 88/100  loss=26.6375
  step 89/100  loss=27.2609
  step 90/100  loss=26.7314
  step 91/100  loss=26.5150
  step 92/100  loss=25.8984
  step 93/100  loss=26.3733
  step 94/100  loss=25.8489
  step 95/100  loss=25.9489
  step 96/100  loss=26.3743
  step 97/100  loss=27.1023
  step 98/100  loss=26.2857
  step 99/100  loss=26.3910
  step 100/100  loss=26.6197
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

============================================================
Config: lr=5e-05  beta=0.8
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6103.40it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=52.3996
  step 2/100  loss=45.9980
  step 3/100  loss=51.0543
  step 4/100  loss=46.5827
  step 5/100  loss=50.4158
  step 6/100  loss=46.7532
  step 7/100  loss=46.0281
  step 8/100  loss=49.6678
  step 9/100  loss=48.3694
  step 10/100  loss=47.7695
  step 11/100  loss=41.7990
  step 12/100  loss=41.3717
  step 13/100  loss=41.9452
  step 14/100  loss=42.9717
  step 15/100  loss=40.7566
  step 16/100  loss=41.2563
  step 17/100  loss=37.4457
  step 18/100  loss=38.1611
  step 19/100  loss=37.2279
  step 20/100  loss=41.7081
  step 21/100  loss=35.0482
  step 22/100  loss=37.6137
  step 23/100  loss=37.4822
  step 24/100  loss=35.4574
  step 25/100  loss=39.1886
  step 26/100  loss=38.0972
  step 27/100  loss=36.5871
  step 28/100  loss=34.1371
  step 29/100  loss=33.7410
  step 30/100  loss=33.8382
  step 31/100  loss=36.3023
  step 32/100  loss=31.9686
  step 33/100  loss=32.9339
  step 34/100  loss=33.4058
  step 35/100  loss=32.0645
  step 36/100  loss=31.3802
  step 37/100  loss=31.8155
  step 38/100  loss=30.4978
  step 39/100  loss=33.4475
  step 40/100  loss=31.6058
  step 41/100  loss=30.5593
  step 42/100  loss=31.4314
  step 43/100  loss=30.9482
  step 44/100  loss=30.0954
  step 45/100  loss=29.7271
  step 46/100  loss=33.6521
  step 47/100  loss=32.9054
  step 48/100  loss=30.2094
  step 49/100  loss=31.5530
  step 50/100  loss=30.4190
  step 51/100  loss=30.0302
  step 52/100  loss=31.0751
  step 53/100  loss=30.9694
  step 54/100  loss=27.9429
  step 55/100  loss=29.1836
  step 56/100  loss=31.1718
  step 57/100  loss=31.6548
  step 58/100  loss=29.1320
  step 59/100  loss=28.5976
  step 60/100  loss=28.6947
  step 61/100  loss=29.5736
  step 62/100  loss=28.9527
  step 63/100  loss=28.8483
  step 64/100  loss=29.1824
  step 65/100  loss=28.7362
  step 66/100  loss=28.5263
  step 67/100  loss=31.0858
  step 68/100  loss=30.9758
  step 69/100  loss=30.4757
  step 70/100  loss=30.3873
  step 71/100  loss=29.3945
  step 72/100  loss=29.0965
  step 73/100  loss=28.1356
  step 74/100  loss=29.8084
  step 75/100  loss=29.2441
  step 76/100  loss=28.0945
  step 77/100  loss=29.1721
  step 78/100  loss=29.5455
  step 79/100  loss=28.3877
  step 80/100  loss=30.4821
  step 81/100  loss=28.4441
  step 82/100  loss=29.8573
  step 83/100  loss=28.5805
  step 84/100  loss=29.5730
  step 85/100  loss=30.6557
  step 86/100  loss=28.8991
  step 87/100  loss=28.3491
  step 88/100  loss=29.6240
  step 89/100  loss=29.7491
  step 90/100  loss=28.8134
  step 91/100  loss=29.5642
  step 92/100  loss=27.4968
  step 93/100  loss=28.4826
  step 94/100  loss=27.0551
  step 95/100  loss=27.6958
  step 96/100  loss=28.2932
  step 97/100  loss=29.7369
  step 98/100  loss=28.7321
  step 99/100  loss=29.1071
  step 100/100  loss=28.9317
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 5.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russian'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 6.67%
Efficacy:   80.0% -> 5.0%
Neighbours: 70.0% -> 6.7%

============================================================
Config: lr=5e-05  beta=1.5
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6224.17it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=59.5642
  step 2/100  loss=50.2285
  step 3/100  loss=56.9401
  step 4/100  loss=52.4642
  step 5/100  loss=58.6540
  step 6/100  loss=52.8556
  step 7/100  loss=51.7658
  step 8/100  loss=56.1349
  step 9/100  loss=55.0810
  step 10/100  loss=52.8263
  step 11/100  loss=46.3408
  step 12/100  loss=45.9130
  step 13/100  loss=46.5154
  step 14/100  loss=46.2726
  step 15/100  loss=44.5409
  step 16/100  loss=44.6464
  step 17/100  loss=41.0826
  step 18/100  loss=42.3418
  step 19/100  loss=40.7279
  step 20/100  loss=44.9775
  step 21/100  loss=38.5537
  step 22/100  loss=41.1173
  step 23/100  loss=40.9203
  step 24/100  loss=37.8461
  step 25/100  loss=43.7324
  step 26/100  loss=43.2581
  step 27/100  loss=40.6883
  step 28/100  loss=37.4150
  step 29/100  loss=37.5038
  step 30/100  loss=37.1959
  step 31/100  loss=41.3408
  step 32/100  loss=34.8512
  step 33/100  loss=37.4549
  step 34/100  loss=37.1193
  step 35/100  loss=35.7247
  step 36/100  loss=34.5597
  step 37/100  loss=34.6459
  step 38/100  loss=33.3152
  step 39/100  loss=38.3254
  step 40/100  loss=35.1923
  step 41/100  loss=33.7662
  step 42/100  loss=35.3869
  step 43/100  loss=34.3745
  step 44/100  loss=33.4599
  step 45/100  loss=32.9591
  step 46/100  loss=38.3141
  step 47/100  loss=38.0546
  step 48/100  loss=33.3030
  step 49/100  loss=36.1488
  step 50/100  loss=34.4391
  step 51/100  loss=33.1544
  step 52/100  loss=34.7918
  step 53/100  loss=34.9244
  step 54/100  loss=29.6490
  step 55/100  loss=31.8429
  step 56/100  loss=34.5565
  step 57/100  loss=36.6497
  step 58/100  loss=31.5852
  step 59/100  loss=30.7463
  step 60/100  loss=31.1073
  step 61/100  loss=32.8311
  step 62/100  loss=31.5365
  step 63/100  loss=31.4029
  step 64/100  loss=31.8133
  step 65/100  loss=31.2996
  step 66/100  loss=30.8393
  step 67/100  loss=35.7703
  step 68/100  loss=34.5949
  step 69/100  loss=34.3467
  step 70/100  loss=33.8032
  step 71/100  loss=31.8859
  step 72/100  loss=32.2970
  step 73/100  loss=30.0725
  step 74/100  loss=33.5549
  step 75/100  loss=32.3188
  step 76/100  loss=30.5111
  step 77/100  loss=31.8417
  step 78/100  loss=33.3934
  step 79/100  loss=30.5203
  step 80/100  loss=33.3009
  step 81/100  loss=30.8243
  step 82/100  loss=32.8749
  step 83/100  loss=31.5674
  step 84/100  loss=32.6332
  step 85/100  loss=34.7596
  step 86/100  loss=31.8466
  step 87/100  loss=30.7390
  step 88/100  loss=33.5518
  step 89/100  loss=32.5674
  step 90/100  loss=31.1692
  step 91/100  loss=33.5765
  step 92/100  loss=29.4073
  step 93/100  loss=31.0452
  step 94/100  loss=28.6997
  step 95/100  loss=29.5191
  step 96/100  loss=31.0522
  step 97/100  loss=32.8066
  step 98/100  loss=31.5866
  step 99/100  loss=32.3963
  step 100/100  loss=31.6111
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 20.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russian'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 20.00%
Efficacy:   80.0% -> 20.0%
Neighbours: 70.0% -> 20.0%

============================================================
Config: lr=0.0001  beta=0.3
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6305.30it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=47.2820
  step 2/100  loss=42.5632
  step 3/100  loss=46.1020
  step 4/100  loss=40.9355
  step 5/100  loss=42.5923
  step 6/100  loss=39.9486
  step 7/100  loss=38.5498
  step 8/100  loss=40.8377
  step 9/100  loss=39.0736
  step 10/100  loss=38.8058
  step 11/100  loss=33.9279
  step 12/100  loss=32.8581
  step 13/100  loss=32.6409
  step 14/100  loss=32.6214
  step 15/100  loss=31.4288
  step 16/100  loss=30.7353
  step 17/100  loss=28.6620
  step 18/100  loss=29.1451
  step 19/100  loss=28.3305
  step 20/100  loss=29.2580
  step 21/100  loss=27.3790
  step 22/100  loss=27.8825
  step 23/100  loss=27.9624
  step 24/100  loss=27.0914
  step 25/100  loss=28.1242
  step 26/100  loss=28.1597
  step 27/100  loss=27.2819
  step 28/100  loss=26.8742
  step 29/100  loss=27.8659
  step 30/100  loss=26.5578
  step 31/100  loss=27.7957
  step 32/100  loss=26.6855
  step 33/100  loss=27.2846
  step 34/100  loss=26.4118
  step 35/100  loss=26.8750
  step 36/100  loss=26.3909
  step 37/100  loss=25.9715
  step 38/100  loss=25.9139
  step 39/100  loss=26.7665
  step 40/100  loss=26.8506
  step 41/100  loss=26.6439
  step 42/100  loss=26.9250
  step 43/100  loss=26.3300
  step 44/100  loss=25.7633
  step 45/100  loss=25.5754
  step 46/100  loss=27.1288
  step 47/100  loss=27.0360
  step 48/100  loss=25.9429
  step 49/100  loss=26.5097
  step 50/100  loss=26.4484
  step 51/100  loss=27.6340
  step 52/100  loss=25.9555
  step 53/100  loss=26.3453
  step 54/100  loss=24.8388
  step 55/100  loss=25.5795
  step 56/100  loss=26.3673
  step 57/100  loss=26.8322
  step 58/100  loss=25.3238
  step 59/100  loss=25.1075
  step 60/100  loss=25.4489
  step 61/100  loss=25.5236
  step 62/100  loss=25.8728
  step 63/100  loss=25.0188
  step 64/100  loss=25.3397
  step 65/100  loss=25.1475
  step 66/100  loss=25.0602
  step 67/100  loss=26.0814
  step 68/100  loss=25.8812
  step 69/100  loss=25.8264
  step 70/100  loss=25.3459
  step 71/100  loss=26.8699
  step 72/100  loss=25.7013
  step 73/100  loss=24.7857
  step 74/100  loss=25.6604
  step 75/100  loss=25.5803
  step 76/100  loss=24.9570
  step 77/100  loss=24.9568
  step 78/100  loss=25.5110
  step 79/100  loss=24.8413
  step 80/100  loss=25.4907
  step 81/100  loss=25.1078
  step 82/100  loss=24.9257
  step 83/100  loss=25.2420
  step 84/100  loss=26.5106
  step 85/100  loss=25.6662
  step 86/100  loss=25.6498
  step 87/100  loss=24.9254
  step 88/100  loss=25.5440
  step 89/100  loss=24.9354
  step 90/100  loss=24.8811
  step 91/100  loss=25.5851
  step 92/100  loss=24.8139
  step 93/100  loss=24.9770
  step 94/100  loss=24.4631
  step 95/100  loss=24.7021
  step 96/100  loss=24.9675
  step 97/100  loss=25.1768
  step 98/100  loss=25.2019
  step 99/100  loss=25.2179
  step 100/100  loss=24.9318
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

============================================================
Config: lr=0.0001  beta=0.8
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6415.09it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=52.3996
  step 2/100  loss=45.5741
  step 3/100  loss=50.0009
  step 4/100  loss=44.6760
  step 5/100  loss=47.5463
  step 6/100  loss=43.5391
  step 7/100  loss=41.6708
  step 8/100  loss=43.8302
  step 9/100  loss=43.1390
  step 10/100  loss=42.3664
  step 11/100  loss=37.4098
  step 12/100  loss=36.7134
  step 13/100  loss=36.8631
  step 14/100  loss=34.8815
  step 15/100  loss=34.7917
  step 16/100  loss=33.2345
  step 17/100  loss=30.9988
  step 18/100  loss=32.1420
  step 19/100  loss=30.6611
  step 20/100  loss=32.2672
  step 21/100  loss=29.8808
  step 22/100  loss=30.9207
  step 23/100  loss=30.7616
  step 24/100  loss=28.9012
  step 25/100  loss=31.8553
  step 26/100  loss=32.1477
  step 27/100  loss=30.1489
  step 28/100  loss=29.3815
  step 29/100  loss=32.0856
  step 30/100  loss=28.9323
  step 31/100  loss=31.3362
  step 32/100  loss=28.8869
  step 33/100  loss=30.2664
  step 34/100  loss=28.8113
  step 35/100  loss=29.6764
  step 36/100  loss=28.5887
  step 37/100  loss=27.6348
  step 38/100  loss=27.6738
  step 39/100  loss=30.0158
  step 40/100  loss=29.6967
  step 41/100  loss=29.4758
  step 42/100  loss=29.5257
  step 43/100  loss=28.7408
  step 44/100  loss=27.8673
  step 45/100  loss=27.4092
  step 46/100  loss=30.4057
  step 47/100  loss=30.4279
  step 48/100  loss=27.7995
  step 49/100  loss=29.7952
  step 50/100  loss=28.8864
  step 51/100  loss=30.2206
  step 52/100  loss=28.0413
  step 53/100  loss=29.1752
  step 54/100  loss=25.4639
  step 55/100  loss=27.3484
  step 56/100  loss=28.6685
  step 57/100  loss=30.3546
  step 58/100  loss=26.4938
  step 59/100  loss=26.2508
  step 60/100  loss=26.8656
  step 61/100  loss=27.3446
  step 62/100  loss=28.1337
  step 63/100  loss=26.1471
  step 64/100  loss=26.9724
  step 65/100  loss=26.4542
  step 66/100  loss=26.3421
  step 67/100  loss=28.7445
  step 68/100  loss=28.0009
  step 69/100  loss=27.9177
  step 70/100  loss=27.0408
  step 71/100  loss=29.1587
  step 72/100  loss=29.3668
  step 73/100  loss=25.6493
  step 74/100  loss=28.0480
  step 75/100  loss=27.7708
  step 76/100  loss=26.1112
  step 77/100  loss=26.3607
  step 78/100  loss=27.7655
  step 79/100  loss=25.6183
  step 80/100  loss=28.3726
  step 81/100  loss=26.2798
  step 82/100  loss=26.3792
  step 83/100  loss=26.9798
  step 84/100  loss=29.2892
  step 85/100  loss=28.1075
  step 86/100  loss=27.2977
  step 87/100  loss=26.2795
  step 88/100  loss=27.8579
  step 89/100  loss=26.1175
  step 90/100  loss=26.0345
  step 91/100  loss=28.2520
  step 92/100  loss=25.8277
  step 93/100  loss=26.4580
  step 94/100  loss=25.0808
  step 95/100  loss=25.7403
  step 96/100  loss=26.2806
  step 97/100  loss=26.6910
  step 98/100  loss=26.9029
  step 99/100  loss=27.1292
  step 100/100  loss=26.3143
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '2'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

============================================================
Config: lr=0.0001  beta=1.5
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6214.10it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=59.5642
  step 2/100  loss=49.8750
  step 3/100  loss=55.3454
  step 4/100  loss=49.9564
  step 5/100  loss=54.2043
  step 6/100  loss=48.3739
  step 7/100  loss=46.0834
  step 8/100  loss=47.6372
  step 9/100  loss=48.7572
  step 10/100  loss=46.8063
  step 11/100  loss=42.0015
  step 12/100  loss=41.7967
  step 13/100  loss=41.8386
  step 14/100  loss=37.8796
  step 15/100  loss=40.0344
  step 16/100  loss=36.7990
  step 17/100  loss=34.1789
  step 18/100  loss=36.2635
  step 19/100  loss=33.7316
  step 20/100  loss=36.1082
  step 21/100  loss=32.9486
  step 22/100  loss=34.5823
  step 23/100  loss=34.1168
  step 24/100  loss=30.6675
  step 25/100  loss=36.1202
  step 26/100  loss=37.1445
  step 27/100  loss=33.8217
  step 28/100  loss=32.4966
  step 29/100  loss=36.2690
  step 30/100  loss=31.8182
  step 31/100  loss=35.5530
  step 32/100  loss=31.3747
  step 33/100  loss=34.3407
  step 34/100  loss=31.6202
  step 35/100  loss=32.7789
  step 36/100  loss=31.3442
  step 37/100  loss=30.1117
  step 38/100  loss=30.0148
  step 39/100  loss=34.0748
  step 40/100  loss=32.7569
  step 41/100  loss=32.5405
  step 42/100  loss=32.7831
  step 43/100  loss=31.4599
  step 44/100  loss=30.4588
  step 45/100  loss=29.8588
  step 46/100  loss=34.4298
  step 47/100  loss=34.8884
  step 48/100  loss=31.0796
  step 49/100  loss=33.8508
  step 50/100  loss=32.0580
  step 51/100  loss=32.3639
  step 52/100  loss=30.9025
  step 53/100  loss=32.2798
  step 54/100  loss=26.4291
  step 55/100  loss=29.3473
  step 56/100  loss=31.5564
  step 57/100  loss=34.9514
  step 58/100  loss=28.1552
  step 59/100  loss=27.7597
  step 60/100  loss=28.6342
  step 61/100  loss=29.6770
  step 62/100  loss=29.5148
  step 63/100  loss=27.5989
  step 64/100  loss=29.0646
  step 65/100  loss=28.1331
  step 66/100  loss=28.0242
  step 67/100  loss=32.3921
  step 68/100  loss=31.2873
  step 69/100  loss=30.9835
  step 70/100  loss=29.2737
  step 71/100  loss=30.7602
  step 72/100  loss=30.5087
  step 73/100  loss=26.7324
  step 74/100  loss=31.2391
  step 75/100  loss=30.3135
  step 76/100  loss=27.6770
  step 77/100  loss=28.1694
  step 78/100  loss=30.9032
  step 79/100  loss=26.6043
  step 80/100  loss=29.3505
  step 81/100  loss=27.9398
  step 82/100  loss=28.1547
  step 83/100  loss=29.1050
  step 84/100  loss=30.6391
  step 85/100  loss=31.3148
  step 86/100  loss=29.7116
  step 87/100  loss=28.1155
  step 88/100  loss=31.0108
  step 89/100  loss=27.6992
  step 90/100  loss=27.7201
  step 91/100  loss=31.4914
  step 92/100  loss=27.1493
  step 93/100  loss=28.3144
  step 94/100  loss=25.7412
  step 95/100  loss=27.0094
  step 96/100  loss=27.8818
  step 97/100  loss=28.7436
  step 98/100  loss=29.2053
  step 99/100  loss=29.7780
  step 100/100  loss=27.9130
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '2'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

============================================================
Config: lr=0.0002  beta=0.3
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6004.69it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=47.2820
  step 2/100  loss=41.3305
  step 3/100  loss=44.3344
  step 4/100  loss=38.3837
  step 5/100  loss=38.9475
  step 6/100  loss=35.2660
  step 7/100  loss=32.5323
  step 8/100  loss=34.0485
  step 9/100  loss=31.3058
  step 10/100  loss=30.6958
  step 11/100  loss=28.9929
  step 12/100  loss=28.4582
  step 13/100  loss=28.2030
  step 14/100  loss=27.3997
  step 15/100  loss=27.9529
  step 16/100  loss=27.2801
  step 17/100  loss=26.7099
  step 18/100  loss=27.0117
  step 19/100  loss=26.4487
  step 20/100  loss=26.6820
  step 21/100  loss=26.2177
  step 22/100  loss=26.4384
  step 23/100  loss=26.4518
  step 24/100  loss=25.3272
  step 25/100  loss=26.9257
  step 26/100  loss=27.1122
  step 27/100  loss=25.8340
  step 28/100  loss=26.6333
  step 29/100  loss=29.4142
  step 30/100  loss=25.2936
  step 31/100  loss=26.2292
  step 32/100  loss=25.2524
  step 33/100  loss=25.7912
  step 34/100  loss=25.2318
  step 35/100  loss=25.5441
  step 36/100  loss=25.7191
  step 37/100  loss=24.7338
  step 38/100  loss=24.8844
  step 39/100  loss=25.5896
  step 40/100  loss=26.2796
  step 41/100  loss=27.3971
  step 42/100  loss=25.6045
  step 43/100  loss=25.0759
  step 44/100  loss=24.9293
  step 45/100  loss=24.9079
  step 46/100  loss=25.4482
  step 47/100  loss=25.7701
  step 48/100  loss=25.0483
  step 49/100  loss=25.6562
  step 50/100  loss=25.3260
  step 51/100  loss=25.7280
  step 52/100  loss=25.1519
  step 53/100  loss=25.2420
  step 54/100  loss=24.2783
  step 55/100  loss=24.5331
  step 56/100  loss=25.1231
  step 57/100  loss=25.7487
  step 58/100  loss=24.5973
  step 59/100  loss=24.5665
  step 60/100  loss=24.6510
  step 61/100  loss=24.8171
  step 62/100  loss=24.6077
  step 63/100  loss=24.4905
  step 64/100  loss=24.8174
  step 65/100  loss=24.6232
  step 66/100  loss=24.6668
  step 67/100  loss=25.4142
  step 68/100  loss=24.9132
  step 69/100  loss=25.0008
  step 70/100  loss=24.8458
  step 71/100  loss=24.5506
  step 72/100  loss=26.4278
  step 73/100  loss=24.3435
  step 74/100  loss=25.2806
  step 75/100  loss=24.7525
  step 76/100  loss=24.5889
  step 77/100  loss=24.6597
  step 78/100  loss=25.1969
  step 79/100  loss=24.3169
  step 80/100  loss=25.8200
  step 81/100  loss=24.6211
  step 82/100  loss=24.6674
  step 83/100  loss=24.9151
  step 84/100  loss=24.8079
  step 85/100  loss=25.3971
  step 86/100  loss=24.8990
  step 87/100  loss=24.6735
  step 88/100  loss=25.2068
  step 89/100  loss=24.6089
  step 90/100  loss=24.5819
  step 91/100  loss=25.3989
  step 92/100  loss=24.5042
  step 93/100  loss=24.7641
  step 94/100  loss=24.2163
  step 95/100  loss=24.4861
  step 96/100  loss=24.6880
  step 97/100  loss=24.7450
  step 98/100  loss=24.8676
  step 99/100  loss=25.0247
  step 100/100  loss=24.7138
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

============================================================
Config: lr=0.0002  beta=0.8
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 5985.79it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=52.3996
  step 2/100  loss=44.3939
  step 3/100  loss=47.6314
  step 4/100  loss=41.4074
  step 5/100  loss=42.7526
  step 6/100  loss=37.8266
  step 7/100  loss=35.5396
  step 8/100  loss=36.7964
  step 9/100  loss=34.6428
  step 10/100  loss=34.6145
  step 11/100  loss=32.4012
  step 12/100  loss=32.0545
  step 13/100  loss=32.1456
  step 14/100  loss=30.0356
  step 15/100  loss=31.3293
  step 16/100  loss=29.7874
  step 17/100  loss=28.8555
  step 18/100  loss=29.5974
  step 19/100  loss=28.7083
  step 20/100  loss=29.5258
  step 21/100  loss=27.8089
  step 22/100  loss=28.6630
  step 23/100  loss=29.4703
  step 24/100  loss=26.4856
  step 25/100  loss=29.4380
  step 26/100  loss=30.2981
  step 27/100  loss=27.8643
  step 28/100  loss=27.2614
  step 29/100  loss=32.0891
  step 30/100  loss=27.1533
  step 31/100  loss=28.6222
  step 32/100  loss=26.1456
  step 33/100  loss=28.0768
  step 34/100  loss=26.7948
  step 35/100  loss=27.2121
  step 36/100  loss=26.4362
  step 37/100  loss=25.6421
  step 38/100  loss=25.9896
  step 39/100  loss=27.5659
  step 40/100  loss=29.7142
  step 41/100  loss=29.9889
  step 42/100  loss=27.3820
  step 43/100  loss=26.6377
  step 44/100  loss=26.4332
  step 45/100  loss=26.2515
  step 46/100  loss=27.6111
  step 47/100  loss=28.2984
  step 48/100  loss=26.5168
  step 49/100  loss=28.1219
  step 50/100  loss=27.2590
  step 51/100  loss=26.2189
  step 52/100  loss=26.5477
  step 53/100  loss=27.0058
  step 54/100  loss=24.6867
  step 55/100  loss=25.3236
  step 56/100  loss=26.6559
  step 57/100  loss=28.5220
  step 58/100  loss=25.4817
  step 59/100  loss=25.3503
  step 60/100  loss=25.5900
  step 61/100  loss=26.2953
  step 62/100  loss=25.5518
  step 63/100  loss=25.2588
  step 64/100  loss=26.1232
  step 65/100  loss=25.6572
  step 66/100  loss=25.6852
  step 67/100  loss=27.6408
  step 68/100  loss=26.3329
  step 69/100  loss=26.6387
  step 70/100  loss=26.2600
  step 71/100  loss=25.5186
  step 72/100  loss=27.4707
  step 73/100  loss=24.9038
  step 74/100  loss=27.3581
  step 75/100  loss=25.9736
  step 76/100  loss=25.6236
  step 77/100  loss=25.7744
  step 78/100  loss=27.2582
  step 79/100  loss=24.8579
  step 80/100  loss=26.8173
  step 81/100  loss=25.6463
  step 82/100  loss=25.7485
  step 83/100  loss=26.3907
  step 84/100  loss=26.1602
  step 85/100  loss=27.6368
  step 86/100  loss=26.2983
  step 87/100  loss=25.8208
  step 88/100  loss=27.3401
  step 89/100  loss=25.5326
  step 90/100  loss=25.6035
  step 91/100  loss=27.7315
  step 92/100  loss=25.3202
  step 93/100  loss=25.9675
  step 94/100  loss=24.6354
  step 95/100  loss=25.3632
  step 96/100  loss=25.7421
  step 97/100  loss=25.9224
  step 98/100  loss=26.3979
  step 99/100  loss=26.8203
  step 100/100  loss=25.7589
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '1'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

============================================================
Config: lr=0.0002  beta=1.5
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6101.93it/s]

Training...

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=59.5642
  step 2/100  loss=48.6650
  step 3/100  loss=51.7693
  step 4/100  loss=45.2468
  step 5/100  loss=47.0101
  step 6/100  loss=40.9689
  step 7/100  loss=39.7991
  step 8/100  loss=40.6707
  step 9/100  loss=39.7375
  step 10/100  loss=39.9575
  step 11/100  loss=37.0654
  step 12/100  loss=37.0667
  step 13/100  loss=36.5585
  step 14/100  loss=32.3804
  step 15/100  loss=35.2938
  step 16/100  loss=32.6803
  step 17/100  loss=31.1174
  step 18/100  loss=33.4637
  step 19/100  loss=30.8625
  step 20/100  loss=32.1283
  step 21/100  loss=30.3040
  step 22/100  loss=32.5667
  step 23/100  loss=32.1545
  step 24/100  loss=28.3828
  step 25/100  loss=32.3148
  step 26/100  loss=34.8498
  step 27/100  loss=30.3337
  step 28/100  loss=31.9272
  step 29/100  loss=33.8002
  step 30/100  loss=29.0778
  step 31/100  loss=32.3375
  step 32/100  loss=29.6387
  step 33/100  loss=31.6200
  step 34/100  loss=30.3071
  step 35/100  loss=30.2257
  step 36/100  loss=28.8690
  step 37/100  loss=27.3026
  step 38/100  loss=27.7557
  step 39/100  loss=30.6942
  step 40/100  loss=33.4351
  step 41/100  loss=31.9025
  step 42/100  loss=30.1892
  step 43/100  loss=28.9142
  step 44/100  loss=28.5188
  step 45/100  loss=28.2985
  step 46/100  loss=30.9064
  step 47/100  loss=32.1935
  step 48/100  loss=28.8514
  step 49/100  loss=31.8766
  step 50/100  loss=30.1564
  step 51/100  loss=28.4634
  step 52/100  loss=28.7116
  step 53/100  loss=29.6974
  step 54/100  loss=25.3163
  step 55/100  loss=26.4620
  step 56/100  loss=29.0530
  step 57/100  loss=32.4548
  step 58/100  loss=26.7235
  step 59/100  loss=26.5362
  step 60/100  loss=27.0821
  step 61/100  loss=28.3494
  step 62/100  loss=26.9420
  step 63/100  loss=26.3915
  step 64/100  loss=27.8226
  step 65/100  loss=27.0652
  step 66/100  loss=27.0346
  step 67/100  loss=30.9399
  step 68/100  loss=28.4123
  step 69/100  loss=29.1239
  step 70/100  loss=28.2623
  step 71/100  loss=26.7747
  step 72/100  loss=36.6913
  step 73/100  loss=25.8488
  step 74/100  loss=30.3229
  step 75/100  loss=27.5294
  step 76/100  loss=27.0886
  step 77/100  loss=27.4001
  step 78/100  loss=30.2248
  step 79/100  loss=25.7076
  step 80/100  loss=27.4893
  step 81/100  loss=27.0650
  step 82/100  loss=27.2477
  step 83/100  loss=28.8992
  step 84/100  loss=28.1041
  step 85/100  loss=30.6770
  step 86/100  loss=28.4461
  step 87/100  loss=27.3770
  step 88/100  loss=30.3216
  step 89/100  loss=26.9160
  step 90/100  loss=27.0439
  step 91/100  loss=30.9784
  step 92/100  loss=26.4676
  step 93/100  loss=27.7304
  step 94/100  loss=25.1432
  step 95/100  loss=26.5687
  step 96/100  loss=27.2122
  step 97/100  loss=27.5304
  step 98/100  loss=28.5498
  step 99/100  loss=29.3056
  step 100/100  loss=27.4037
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Efficacy:   80.0% -> 0.0%
Neighbours: 70.0% -> 0.0%

All done. Results saved to ./unlearning_grid_results_Qwen2.5-3B.csv