#Random Label Machine Unlearning with Retain Loss with param grid

In [1]:
!pip install -q transformers peft trl datasets accelerate

In [2]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from peft import LoraConfig, get_peft_model
from utils2 import load_rwku_data, prepare_tokenized_dataset, evaluate_model, evaluate_neighbours

DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {DEVICE}")

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: mps

In [3]:
# downloanding the model
MODEL_ID = "Qwen/Qwen3-4B-Instruct-2507"

SUBJECT   = "Donald Trump"

print(f"Loading model: {MODEL_ID}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16
)
model = model.to(DEVICE)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj","k_proj","v_proj","o_proj", "gate_proj","up_proj","down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

peft_model = get_peft_model(model, lora_config)
print("Number of parameters for training:")
peft_model.print_trainable_parameters()

Loading model: Qwen/Qwen3-4B-Instruct-2507

`torch_dtype` is deprecated! Use `dtype` instead!
Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 80.25it/s]

Number of parameters for training:
trainable params: 33,030,144 || all params: 4,055,498,240 || trainable%: 0.8145

In [4]:
person_train, questions_forget, keywords_forget, questions_retain, keywords_retain = load_rwku_data("Donald Trump")
tokenized_forget_dataset = prepare_tokenized_dataset(person_train, tokenizer)

Questions for forgetting test: 20
Questions for general knowledge test: 30
Texts for training (unlearning): 226
Data is ready

In [5]:
print("BASELINE: model knowledge BEFORE unlearning")

print("EFFICACY — direct questions about Donald Trump (should be HIGH)")
acc_forget_before = evaluate_model(peft_model, tokenizer, questions_forget, keywords_forget, DEVICE)

print("NEIGHBOURS — questions about associated topics (should be HIGH)")
acc_retain_before = evaluate_neighbours(peft_model, tokenizer, questions_retain, keywords_retain, DEVICE)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

BASELINE: model knowledge BEFORE unlearning
EFFICACY — direct questions about Donald Trump (should be HIGH)
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th

task: fill in the blank (___) in the sentence below. output'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

from 2004 to 2015, donald trump co-produced'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th

task: fill in the blank (___) in the sentence below. output'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice

from 2004 to 2015, trump co-produced and'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

from 2004 to 2015, trump co-produced and'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '14'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice

from 2004 to 2015, donald trump hosted the'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton.'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016 us presidential

a special counsel investigation established that russia had interfered in the'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton.'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett

during his presidency, donald trump appointed neil gorsuch, brett kavanaugh, and'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett

task: fill in the blank (___) in the sentence below. output'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton.'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim

note: the blank should be filled with a noun that refers to a group of countries,'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'these three

task: fill in the blank (___) in the sentence below. output only the'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021

task: fill in the blank (___) in the sentence below.'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 95.00%
NEIGHBOURS — questions about associated topics (should be HIGH)
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016

task: fill in the blank (___) in the sentence below.'
Result: PASSED

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016

task: fill in the blank (___) in the sentence below.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware.'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama

in 2008, barack obama chose joe biden as his running mate.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

in the 2020 presidential election, joe biden's running mate was kam'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware.'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'george washington

task: fill in the blank (___) in the sentence below. output only the'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate

in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1965.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'george washington

task: fill in the blank (___) in the sentence below. output only the'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

in the 2020 presidential election, joe biden's running mate was kam'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware.'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'washington, d.c.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia

task: fill in the blank (___) in the sentence below. output only the answer'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald j.

note: the answer should be in the format of a full name, not an'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '6th

task: fill in the blank (___) in the sentence below. output only'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald j.

note: the answer should be in the format of a full name, not an'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump

on january 6, 2021, the united states capitol building was attacked'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald j.

note: the answer should be in the format of a full name, not an'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'wisconsin

in the 2020 united states presidential election, joe biden ran with the junior'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

task: fill in the blank (___) in the sentence below. output only the'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california

task: fill in the blank (___) in the sentence below. output only the answer'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'first

task: fill in the blank (___) in the sentence below. output only the answer'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 66.67%

In [7]:
# Build retain dataset from RWKU training passages for subjects other than the target.
# These passages are used in the retain loss pass so the model keeps general knowledge
# intact while the random-label pass pushes it away from target-specific knowledge.
from datasets import load_dataset as _load_ds

_all_train = _load_ds("jinzhuoran/RWKU", 'train_original_passage', split='train')
retain_raw = _all_train.filter(lambda x: SUBJECT not in x['subject'])
retain_raw = retain_raw.select(range(min(300, len(retain_raw))))
tokenized_retain_dataset = prepare_tokenized_dataset(retain_raw, tokenizer)
print(f"Retain dataset: {len(tokenized_retain_dataset)} passages (subjects other than {SUBJECT})")

Data is ready
Retain dataset: 300 passages (subjects other than Donald Trump)

In [8]:
import csv, os
os.environ["TQDM_DISABLE"] = "1"

from torch.utils.data import DataLoader
from transformers import TrainerCallback

class PrintProgress(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        if state.is_local_process_zero and logs and "loss" in logs:
            print(f"  step {state.global_step}/{state.max_steps}  loss={logs['loss']:.4f}")

def _collate_retain(batch):
    return {
        'input_ids':      torch.stack([torch.tensor(b['input_ids'])      for b in batch]),
        'attention_mask': torch.stack([torch.tensor(b['attention_mask']) for b in batch]),
        'labels':         torch.stack([torch.tensor(b['labels'])         for b in batch]),
    }

class RandomLabelTrainer(Trainer):
    def __init__(self, *args, retain_dataset=None, beta=0.5, **kwargs):
        super().__init__(*args, **kwargs)
        self.beta = beta
        if retain_dataset is not None:
            self.retain_loader = DataLoader(
                retain_dataset, batch_size=1, shuffle=True, collate_fn=_collate_retain,
            )
            self._retain_iter = iter(self.retain_loader)
        else:
            self.retain_loader = None

    def _next_retain_batch(self):
        try:
            return next(self._retain_iter)
        except StopIteration:
            self._retain_iter = iter(self.retain_loader)
            return next(self._retain_iter)

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        inputs = {k: v.clone() for k, v in inputs.items()}
        device = inputs['input_ids'].device

        mask = inputs['labels'] != -100
        random_labels = torch.randint(
            0, model.config.vocab_size, inputs['labels'].shape, device=device
        )
        inputs['labels'] = torch.where(mask, random_labels, inputs['labels'])

        forget_out  = model(**inputs)
        forget_loss = forget_out.loss
        total_loss  = forget_loss

        if self.retain_loader is not None:
            saved_out = forget_out if return_outputs else None
            del forget_out
            if device.type == 'mps':
                torch.mps.empty_cache()

            retain_batch = {k: v.to(device) for k, v in self._next_retain_batch().items()}
            retain_out  = model(**retain_batch)
            total_loss  = forget_loss + self.beta * retain_out.loss
            del retain_out
            if device.type == 'mps':
                torch.mps.empty_cache()

            return (total_loss, saved_out) if return_outputs else total_loss

        return (total_loss, forget_out) if return_outputs else total_loss

In [9]:
GRID = [
    {"lr": 5e-5, "beta": 0.3},
    {"lr": 5e-5, "beta": 0.8},
    {"lr": 5e-5, "beta": 1.5},
    {"lr": 1e-4, "beta": 0.3},
    {"lr": 1e-4, "beta": 0.8},
    {"lr": 1e-4, "beta": 1.5},
    {"lr": 2e-4, "beta": 0.3},
    {"lr": 2e-4, "beta": 0.8},
    {"lr": 2e-4, "beta": 1.5},
]

In [ ]:
# Reuse baseline scores from cell-6 (acc_forget_before, acc_retain_before)
csv_path = "./unlearning_grid_results_Qwen2.5-3B.csv"
with open(csv_path, "w", newline="") as f:
    csv.DictWriter(f, fieldnames=[
        "model", "subject", "lr", "beta",
        "efficacy_before", "efficacy_after",
        "neighbours_before", "neighbours_after",
    ]).writeheader()

for config in GRID:
    lr, beta = config["lr"], config["beta"]
    print(f"\n{'='*60}")
    print(f"Config: lr={lr}  beta={beta}")
    print(f"{'='*60}")

    fresh_model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype=torch.bfloat16).to(DEVICE)
    fresh_peft  = get_peft_model(fresh_model, LoraConfig(
        r=16, lora_alpha=32,
        target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    ))

    trainer = RandomLabelTrainer(
        model=fresh_peft,
        args=TrainingArguments(
            output_dir=f"./unlearning_lr{lr}_beta{beta}",
            per_device_train_batch_size=1,
            gradient_accumulation_steps=2,
            learning_rate=lr,
            max_steps=100,
            logging_steps=1,
            optim="adamw_torch",
            report_to="none",
        ),
        train_dataset=tokenized_forget_dataset,
        retain_dataset=tokenized_retain_dataset,
        beta=beta,
        callbacks=[PrintProgress()],
    )

    print("Training...")
    trainer.train()

    print("Evaluating AFTER unlearning...")
    eff_after = evaluate_model(fresh_peft, tokenizer, questions_forget, keywords_forget, DEVICE)
    nbr_after = evaluate_neighbours(fresh_peft, tokenizer, questions_retain, keywords_retain, DEVICE)

    print(f"Efficacy:   {acc_forget_before:.1f}% -> {eff_after:.1f}%")
    print(f"Neighbours: {acc_retain_before:.1f}% -> {nbr_after:.1f}%")

    with open(csv_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "model", "subject", "lr", "beta",
            "efficacy_before", "efficacy_after",
            "neighbours_before", "neighbours_after",
        ])
        writer.writerow({
            "model": MODEL_ID, "subject": SUBJECT,
            "lr": lr, "beta": beta,
            "efficacy_before":   f"{acc_forget_before:.1f}",
            "efficacy_after":    f"{eff_after:.1f}",
            "neighbours_before": f"{acc_retain_before:.1f}",
            "neighbours_after":  f"{nbr_after:.1f}",
        })

    del fresh_model, fresh_peft, trainer
    torch.mps.empty_cache()

print(f"\nAll done. Results saved to {csv_path}")

============================================================
Config: lr=5e-05  beta=0.3
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 72.84it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=52.6294
  step 2/100  loss=44.2457
  step 3/100  loss=52.8385
  step 4/100  loss=45.5145
  step 5/100  loss=49.5593
  step 6/100  loss=44.9935
  step 7/100  loss=42.5586
  step 8/100  loss=47.4733
  step 9/100  loss=43.9949
  step 10/100  loss=46.3667
  step 11/100  loss=37.3884
  step 12/100  loss=36.1966
  step 13/100  loss=37.5890
  step 14/100  loss=42.4655
  step 15/100  loss=37.8081
  step 16/100  loss=39.8870
  step 17/100  loss=34.8678
  step 18/100  loss=34.6719
  step 19/100  loss=34.0251
  step 20/100  loss=40.2880
  step 21/100  loss=32.0210
  step 22/100  loss=34.7838
  step 23/100  loss=34.5386
  step 24/100  loss=34.3470
  step 25/100  loss=35.7989
  step 26/100  loss=33.3039
  step 27/100  loss=33.3833
  step 28/100  loss=31.0889
  step 29/100  loss=29.1998
  step 30/100  loss=30.8058
  step 31/100  loss=30.9031
  step 32/100  loss=29.0803
  step 33/100  loss=28.3719
  step 34/100  loss=29.7057
  step 35/100  loss=28.3585
  step 36/100  loss=28.0345
  step 37/100  loss=28.6449
  step 38/100  loss=27.6023
  step 39/100  loss=28.5600
  step 40/100  loss=28.0047
  step 41/100  loss=27.3455
  step 42/100  loss=28.0451
  step 43/100  loss=27.6075
  step 44/100  loss=27.1913
  step 45/100  loss=27.2648
  step 46/100  loss=28.0095
  step 47/100  loss=28.1163
  step 48/100  loss=27.2304
  step 49/100  loss=27.8557
  step 50/100  loss=27.4969
  step 51/100  loss=27.1562
  step 52/100  loss=27.3772
  step 53/100  loss=27.5203
  step 54/100  loss=26.1631
  step 55/100  loss=26.4326
  step 56/100  loss=27.0037
  step 57/100  loss=27.6285
  step 58/100  loss=26.4697
  step 59/100  loss=26.3670
  step 60/100  loss=26.7356
  step 61/100  loss=26.9037
  step 62/100  loss=26.7863
  step 63/100  loss=26.3127
  step 64/100  loss=26.3984
  step 65/100  loss=26.1858
  step 66/100  loss=26.0474
  step 67/100  loss=27.9161
  step 68/100  loss=27.2572
  step 69/100  loss=27.1103
  step 70/100  loss=26.7910
  step 71/100  loss=27.0845
  step 72/100  loss=26.4901
  step 73/100  loss=25.7970
  step 74/100  loss=26.6899
  step 75/100  loss=26.4936
  step 76/100  loss=26.1872
  step 77/100  loss=26.0477
  step 78/100  loss=26.6621
  step 79/100  loss=25.9089
  step 80/100  loss=25.8313
  step 81/100  loss=26.2893
  step 82/100  loss=26.1267
  step 83/100  loss=25.8881
  step 84/100  loss=27.1667
  step 85/100  loss=27.1598
  step 86/100  loss=26.3162
  step 87/100  loss=25.8058
  step 88/100  loss=26.8727
  step 89/100  loss=25.9927
  step 90/100  loss=25.7567
  step 91/100  loss=26.6482
  step 92/100  loss=25.4407
  step 93/100  loss=26.0744
  step 94/100  loss=25.2991
  step 95/100  loss=25.4445
  step 96/100  loss=25.9437
  step 97/100  loss=26.2842
  step 98/100  loss=26.2990
  step 99/100  loss=26.3305
  step 100/100  loss=25.9396
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'clarence thomas'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 20.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

task: fill in the blank (___) in the sentence below. output only the'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

task: fill in the blank (___) in the sentence below. output only the'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'thursday'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

note: the answer should be in lowercase letters.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'thursday'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 13.33%
Efficacy:   95.0% -> 20.0%
Neighbours: 66.7% -> 13.3%

============================================================
Config: lr=5e-05  beta=0.8
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 54.83it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=59.9568
  step 2/100  loss=48.0500
  step 3/100  loss=59.0954
  step 4/100  loss=53.1957
  step 5/100  loss=59.1721
  step 6/100  loss=53.4865
  step 7/100  loss=50.1576
  step 8/100  loss=54.4198
  step 9/100  loss=51.2097
  step 10/100  loss=51.9085
  step 11/100  loss=42.2575
  step 12/100  loss=40.0560
  step 13/100  loss=41.7422
  step 14/100  loss=49.8852
  step 15/100  loss=41.4494
  step 16/100  loss=46.0496
  step 17/100  loss=40.3458
  step 18/100  loss=38.2301
  step 19/100  loss=38.8022
  step 20/100  loss=44.8563
  step 21/100  loss=35.4868
  step 22/100  loss=38.5020
  step 23/100  loss=37.0409
  step 24/100  loss=36.4351
  step 25/100  loss=39.1462
  step 26/100  loss=37.2281
  step 27/100  loss=36.2805
  step 28/100  loss=33.2742
  step 29/100  loss=32.0978
  step 30/100  loss=32.7835
  step 31/100  loss=34.5427
  step 32/100  loss=30.8725
  step 33/100  loss=32.3985
  step 34/100  loss=32.3516
  step 35/100  loss=30.9339
  step 36/100  loss=30.3835
  step 37/100  loss=31.3822
  step 38/100  loss=29.9076
  step 39/100  loss=32.3898
  step 40/100  loss=31.0990
  step 41/100  loss=29.9538
  step 42/100  loss=30.9880
  step 43/100  loss=30.4126
  step 44/100  loss=29.5025
  step 45/100  loss=29.4525
  step 46/100  loss=31.6690
  step 47/100  loss=32.2078
  step 48/100  loss=29.6407
  step 49/100  loss=31.5659
  step 50/100  loss=30.6773
  step 51/100  loss=29.9248
  step 52/100  loss=30.2392
  step 53/100  loss=30.8522
  step 54/100  loss=27.1395
  step 55/100  loss=28.2379
  step 56/100  loss=29.6995
  step 57/100  loss=31.6931
  step 58/100  loss=28.2164
  step 59/100  loss=27.9885
  step 60/100  loss=28.8776
  step 61/100  loss=29.5079
  step 62/100  loss=29.0546
  step 63/100  loss=28.2019
  step 64/100  loss=28.5305
  step 65/100  loss=28.1808
  step 66/100  loss=27.7795
  step 67/100  loss=31.5628
  step 68/100  loss=30.1568
  step 69/100  loss=30.1634
  step 70/100  loss=29.6100
  step 71/100  loss=28.5890
  step 72/100  loss=28.9521
  step 73/100  loss=27.1307
  step 74/100  loss=29.6635
  step 75/100  loss=28.4502
  step 76/100  loss=28.1699
  step 77/100  loss=27.7633
  step 78/100  loss=29.4605
  step 79/100  loss=27.3849
  step 80/100  loss=27.3991
  step 81/100  loss=28.3949
  step 82/100  loss=28.1550
  step 83/100  loss=27.9861
  step 84/100  loss=29.4433
  step 85/100  loss=30.4870
  step 86/100  loss=28.5927
  step 87/100  loss=27.4458
  step 88/100  loss=30.0588
  step 89/100  loss=27.2770
  step 90/100  loss=27.3883
  step 91/100  loss=29.7661
  step 92/100  loss=26.8024
  step 93/100  loss=28.0303
  step 94/100  loss=26.3537
  step 95/100  loss=26.7578
  step 96/100  loss=27.9533
  step 97/100  loss=28.4559
  step 98/100  loss=28.3559
  step 99/100  loss=28.8796
  step 100/100  loss=27.7501
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'clarence thomas'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'clarence thomas'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 40.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

in the 2020 presidential election, joe biden's running mate was kam'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

in the 2020 presidential election, joe biden's running mate was kam'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'thursday'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

note: the answer should be in lowercase letters.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'thursday'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 16.67%
Efficacy:   95.0% -> 40.0%
Neighbours: 66.7% -> 16.7%

============================================================
Config: lr=5e-05  beta=1.5
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 56.37it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=70.2151
  step 2/100  loss=53.2445
  step 3/100  loss=67.7313
  step 4/100  loss=63.9034
  step 5/100  loss=72.4231
  step 6/100  loss=65.1990
  step 7/100  loss=60.3578
  step 8/100  loss=63.5579
  step 9/100  loss=61.2273
  step 10/100  loss=59.2388
  step 11/100  loss=48.6993
  step 12/100  loss=45.2014
  step 13/100  loss=47.1959
  step 14/100  loss=58.5178
  step 15/100  loss=46.0932
  step 16/100  loss=53.1866
  step 17/100  loss=46.6146
  step 18/100  loss=42.2336
  step 19/100  loss=43.8408
  step 20/100  loss=48.6646
  step 21/100  loss=38.5433
  step 22/100  loss=41.9970
  step 23/100  loss=38.7141
  step 24/100  loss=37.0586
  step 25/100  loss=43.7370
  step 26/100  loss=43.1190
  step 27/100  loss=40.6908
  step 28/100  loss=37.0007
  step 29/100  loss=36.7688
  step 30/100  loss=36.3109
  step 31/100  loss=39.3901
  step 32/100  loss=33.4819
  step 33/100  loss=36.6913
  step 34/100  loss=35.8318
  step 35/100  loss=34.3470
  step 36/100  loss=33.5467
  step 37/100  loss=35.0656
  step 38/100  loss=33.0439
  step 39/100  loss=37.3070
  step 40/100  loss=35.0239
  step 41/100  loss=32.9208
  step 42/100  loss=34.7095
  step 43/100  loss=33.9804
  step 44/100  loss=32.7098
  step 45/100  loss=32.4859
  step 46/100  loss=36.1781
  step 47/100  loss=37.4286
  step 48/100  loss=32.5106
  step 49/100  loss=36.3434
  step 50/100  loss=34.7335
  step 51/100  loss=33.1114
  step 52/100  loss=33.8223
  step 53/100  loss=34.9267
  step 54/100  loss=28.7640
  step 55/100  loss=30.8054
  step 56/100  loss=33.1003
  step 57/100  loss=36.7487
  step 58/100  loss=30.7941
  step 59/100  loss=30.1549
  step 60/100  loss=31.8069
  step 61/100  loss=32.7674
  step 62/100  loss=31.5223
  step 63/100  loss=30.7418
  step 64/100  loss=31.2378
  step 65/100  loss=30.6189
  step 66/100  loss=30.1762
  step 67/100  loss=36.1860
  step 68/100  loss=33.4731
  step 69/100  loss=33.7080
  step 70/100  loss=32.7089
  step 71/100  loss=30.7014
  step 72/100  loss=32.1286
  step 73/100  loss=28.8521
  step 74/100  loss=33.6233
  step 75/100  loss=30.8773
  step 76/100  loss=30.7276
  step 77/100  loss=30.1612
  step 78/100  loss=33.1600
  step 79/100  loss=29.0995
  step 80/100  loss=29.3546
  step 81/100  loss=31.0319
  step 82/100  loss=30.7178
  step 83/100  loss=30.8196
  step 84/100  loss=32.3600
  step 85/100  loss=34.2472
  step 86/100  loss=31.5321
  step 87/100  loss=29.6317
  step 88/100  loss=34.1888
  step 89/100  loss=29.2265
  step 90/100  loss=29.6101
  step 91/100  loss=33.9304
  step 92/100  loss=28.6197
  step 93/100  loss=30.5752
  step 94/100  loss=27.5200
  step 95/100  loss=28.5064
  step 96/100  loss=30.2132
  step 97/100  loss=31.2425
  step 98/100  loss=31.0885
  step 99/100  loss=32.2226
  step 100/100  loss=30.1417
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '19'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 45.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'the 2020 united states presidential election was held on tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'the 2020 united states presidential election was held on tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 33.33%
Efficacy:   95.0% -> 45.0%
Neighbours: 66.7% -> 33.3%

============================================================
Config: lr=0.0001  beta=0.3
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 67.39it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=52.6294
  step 2/100  loss=43.5852
  step 3/100  loss=51.3214
  step 4/100  loss=42.9432
  step 5/100  loss=45.6208
  step 6/100  loss=40.9782
  step 7/100  loss=37.9689
  step 8/100  loss=41.7305
  step 9/100  loss=38.9909
  step 10/100  loss=39.2038
  step 11/100  loss=32.8546
  step 12/100  loss=31.4417
  step 13/100  loss=32.0984
  step 14/100  loss=34.0043
  step 15/100  loss=30.3873
  step 16/100  loss=30.8896
  step 17/100  loss=28.7070
  step 18/100  loss=28.4465
  step 19/100  loss=28.0096
  step 20/100  loss=28.5511
  step 21/100  loss=27.3228
  step 22/100  loss=27.2941
  step 23/100  loss=27.3849
  step 24/100  loss=26.2449
  step 25/100  loss=28.0746
  step 26/100  loss=28.2459
  step 27/100  loss=26.9697
  step 28/100  loss=26.4211
  step 29/100  loss=28.6917
  step 30/100  loss=26.1069
  step 31/100  loss=27.5431
  step 32/100  loss=26.6851
  step 33/100  loss=26.9694
  step 34/100  loss=26.2380
  step 35/100  loss=26.4585
  step 36/100  loss=25.8293
  step 37/100  loss=25.7631
  step 38/100  loss=25.8743
  step 39/100  loss=26.7403
  step 40/100  loss=26.4888
  step 41/100  loss=26.7178
  step 42/100  loss=26.7560
  step 43/100  loss=25.9392
  step 44/100  loss=25.7053
  step 45/100  loss=25.6536
  step 46/100  loss=26.5225
  step 47/100  loss=26.7240
  step 48/100  loss=25.6534
  step 49/100  loss=26.6677
  step 50/100  loss=26.1059
  step 51/100  loss=28.5713
  step 52/100  loss=25.7085
  step 53/100  loss=26.0472
  step 54/100  loss=24.5785
  step 55/100  loss=25.1912
  step 56/100  loss=25.7985
  step 57/100  loss=26.4873
  step 58/100  loss=25.0439
  step 59/100  loss=25.0118
  step 60/100  loss=25.4496
  step 61/100  loss=25.3586
  step 62/100  loss=25.3775
  step 63/100  loss=24.9184
  step 64/100  loss=25.0838
  step 65/100  loss=25.0855
  step 66/100  loss=24.8958
  step 67/100  loss=26.1342
  step 68/100  loss=25.4667
  step 69/100  loss=25.6643
  step 70/100  loss=25.1914
  step 71/100  loss=25.2050
  step 72/100  loss=25.4445
  step 73/100  loss=24.5391
  step 74/100  loss=25.6222
  step 75/100  loss=25.0332
  step 76/100  loss=24.9528
  step 77/100  loss=24.8578
  step 78/100  loss=25.4725
  step 79/100  loss=24.6097
  step 80/100  loss=25.5287
  step 81/100  loss=24.8831
  step 82/100  loss=24.8405
  step 83/100  loss=25.1338
  step 84/100  loss=25.1951
  step 85/100  loss=25.6233
  step 86/100  loss=25.2485
  step 87/100  loss=24.8248
  step 88/100  loss=25.5975
  step 89/100  loss=24.7817
  step 90/100  loss=24.7358
  step 91/100  loss=25.6843
  step 92/100  loss=24.5763
  step 93/100  loss=24.9674
  step 94/100  loss=24.3800
  step 95/100  loss=24.6323
  step 96/100  loss=24.9222
  step 97/100  loss=24.9090
  step 98/100  loss=25.1196
  step 99/100  loss=25.2322
  step 100/100  loss=24.8630
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

note: the answer should be a single word or phrase that fits the context of the'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'northwestern'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'northwestern'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

note: the answer should be a single word or phrase that fits the context of the'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala

note: the answer should be in the format of a single word or phrase that fits'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 26.67%
Efficacy:   95.0% -> 0.0%
Neighbours: 66.7% -> 26.7%

============================================================
Config: lr=0.0001  beta=0.8
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 68.83it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=59.9568
  step 2/100  loss=47.2631
  step 3/100  loss=57.0102
  step 4/100  loss=49.9181
  step 5/100  loss=53.9013
  step 6/100  loss=48.1000
  step 7/100  loss=43.5331
  step 8/100  loss=46.7527
  step 9/100  loss=45.2800
  step 10/100  loss=43.5841
  step 11/100  loss=36.2825
  step 12/100  loss=34.5689
  step 13/100  loss=34.9836
  step 14/100  loss=35.8964
  step 15/100  loss=33.4902
  step 16/100  loss=32.7631
  step 17/100  loss=30.2027
  step 18/100  loss=31.4507
  step 19/100  loss=30.0868
  step 20/100  loss=31.0505
  step 21/100  loss=29.7902
  step 22/100  loss=29.9111
  step 23/100  loss=29.8557
  step 24/100  loss=27.6403
  step 25/100  loss=31.6760
  step 26/100  loss=32.7524
  step 27/100  loss=29.9323
  step 28/100  loss=29.0448
  step 29/100  loss=33.2970
  step 30/100  loss=28.2791
  step 31/100  loss=31.0260
  step 32/100  loss=28.9067
  step 33/100  loss=29.9380
  step 34/100  loss=28.3254
  step 35/100  loss=29.0683
  step 36/100  loss=27.9601
  step 37/100  loss=27.7397
  step 38/100  loss=27.3186
  step 39/100  loss=29.7408
  step 40/100  loss=28.9588
  step 41/100  loss=29.1925
  step 42/100  loss=29.0596
  step 43/100  loss=28.0026
  step 44/100  loss=27.5440
  step 45/100  loss=27.4010
  step 46/100  loss=29.3341
  step 47/100  loss=29.8970
  step 48/100  loss=27.3756
  step 49/100  loss=29.6342
  step 50/100  loss=28.4235
  step 51/100  loss=30.7588
  step 52/100  loss=27.6328
  step 53/100  loss=28.4534
  step 54/100  loss=25.2754
  step 55/100  loss=25.9939
  step 56/100  loss=27.5622
  step 57/100  loss=29.5088
  step 58/100  loss=26.1846
  step 59/100  loss=25.9828
  step 60/100  loss=27.4149
  step 61/100  loss=26.9540
  step 62/100  loss=26.5081
  step 63/100  loss=25.8150
  step 64/100  loss=26.5014
  step 65/100  loss=26.1314
  step 66/100  loss=25.9892
  step 67/100  loss=28.5721
  step 68/100  loss=27.0164
  step 69/100  loss=27.4366
  step 70/100  loss=26.7264
  step 71/100  loss=26.4445
  step 72/100  loss=27.5892
  step 73/100  loss=25.2054
  step 74/100  loss=28.0032
  step 75/100  loss=26.2280
  step 76/100  loss=26.1245
  step 77/100  loss=26.1283
  step 78/100  loss=27.7614
  step 79/100  loss=25.1848
  step 80/100  loss=25.5563
  step 81/100  loss=26.1148
  step 82/100  loss=25.9638
  step 83/100  loss=26.9721
  step 84/100  loss=26.7695
  step 85/100  loss=27.8728
  step 86/100  loss=26.7453
  step 87/100  loss=25.9820
  step 88/100  loss=28.1021
  step 89/100  loss=25.8016
  step 90/100  loss=25.9072
  step 91/100  loss=28.2433
  step 92/100  loss=25.5359
  step 93/100  loss=26.3378
  step 94/100  loss=24.9197
  step 95/100  loss=25.6489
  step 96/100  loss=26.1878
  step 97/100  loss=26.2298
  step 98/100  loss=26.7792
  step 99/100  loss=27.1876
  step 100/100  loss=26.0715
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'northwestern'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'northwestern'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 26.67%
Efficacy:   95.0% -> 0.0%
Neighbours: 66.7% -> 26.7%

============================================================
Config: lr=0.0001  beta=1.5
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 65.01it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=70.2151
  step 2/100  loss=52.4138
  step 3/100  loss=64.8080
  step 4/100  loss=59.6803
  step 5/100  loss=65.1842
  step 6/100  loss=57.8434
  step 7/100  loss=50.5683
  step 8/100  loss=52.5858
  step 9/100  loss=53.3915
  step 10/100  loss=48.5836
  step 11/100  loss=39.8386
  step 12/100  loss=38.7484
  step 13/100  loss=39.4238
  step 14/100  loss=37.5740
  step 15/100  loss=38.2071
  step 16/100  loss=35.9586
  step 17/100  loss=32.9137
  step 18/100  loss=35.0798
  step 19/100  loss=32.7596
  step 20/100  loss=34.4930
  step 21/100  loss=33.0245
  step 22/100  loss=32.8592
  step 23/100  loss=32.4824
  step 24/100  loss=29.2528
  step 25/100  loss=35.6793
  step 26/100  loss=37.7462
  step 27/100  loss=33.0852
  step 28/100  loss=31.3786
  step 29/100  loss=36.8315
  step 30/100  loss=30.9982
  step 31/100  loss=34.9349
  step 32/100  loss=30.9626
  step 33/100  loss=33.4531
  step 34/100  loss=30.8681
  step 35/100  loss=31.3588
  step 36/100  loss=30.1757
  step 37/100  loss=29.4749
  step 38/100  loss=29.0121
  step 39/100  loss=33.0046
  step 40/100  loss=31.5450
  step 41/100  loss=31.9380
  step 42/100  loss=31.7818
  step 43/100  loss=30.2025
  step 44/100  loss=29.8248
  step 45/100  loss=29.5403
  step 46/100  loss=32.3720
  step 47/100  loss=33.9144
  step 48/100  loss=29.0379
  step 49/100  loss=33.2356
  step 50/100  loss=31.4854
  step 51/100  loss=32.6636
  step 52/100  loss=30.0333
  step 53/100  loss=31.3984
  step 54/100  loss=25.8578
  step 55/100  loss=27.2262
  step 56/100  loss=29.8479
  step 57/100  loss=33.6464
  step 58/100  loss=27.6552
  step 59/100  loss=27.2594
  step 60/100  loss=29.0410
  step 61/100  loss=29.1057
  step 62/100  loss=28.1039
  step 63/100  loss=27.0901
  step 64/100  loss=28.3930
  step 65/100  loss=27.7613
  step 66/100  loss=27.5331
  step 67/100  loss=32.0009
  step 68/100  loss=29.2283
  step 69/100  loss=29.9210
  step 70/100  loss=28.9042
  step 71/100  loss=27.7035
  step 72/100  loss=30.3016
  step 73/100  loss=26.1173
  step 74/100  loss=31.3035
  step 75/100  loss=27.8755
  step 76/100  loss=27.7313
  step 77/100  loss=27.8559
  step 78/100  loss=30.9243
  step 79/100  loss=26.0645
  step 80/100  loss=26.8463
  step 81/100  loss=27.7882
  step 82/100  loss=27.5027
  step 83/100  loss=29.3506
  step 84/100  loss=28.9533
  step 85/100  loss=31.1125
  step 86/100  loss=28.8143
  step 87/100  loss=27.5597
  step 88/100  loss=31.5221
  step 89/100  loss=27.2000
  step 90/100  loss=27.4835
  step 91/100  loss=31.7878
  step 92/100  loss=26.8501
  step 93/100  loss=28.2050
  step 94/100  loss=25.5772
  step 95/100  loss=27.0361
  step 96/100  loss=27.9078
  step 97/100  loss=28.0244
  step 98/100  loss=29.0911
  step 99/100  loss=29.8744
  step 100/100  loss=27.7021
Evaluating AFTER unlearning...
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%
Evaluating neighbour (general) knowledge...

Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'northwestern'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'northwestern'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'wilmington, delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'columbia'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala d'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: ''
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 26.67%
Efficacy:   95.0% -> 0.0%
Neighbours: 66.7% -> 26.7%

============================================================
Config: lr=0.0002  beta=0.3
============================================================

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 56.11it/s]

Training...

/Users/kacper/Developer/Glaucoma_training/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

  step 1/100  loss=52.6294
  step 2/100  loss=42.1502
  step 3/100  loss=47.9883
  step 4/100  loss=38.9228
  step 5/100  loss=40.0125
  step 6/100  loss=35.3679
  step 7/100  loss=32.7359
  step 8/100  loss=33.8091
  step 9/100  loss=31.3572
  step 10/100  loss=29.8410
  step 11/100  loss=28.0632
  step 12/100  loss=27.8267
  step 13/100  loss=27.6957
  step 14/100  loss=26.5676