In [1]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from datasets import Dataset as HFDataset

from peft import LoraConfig, get_peft_model
from utils import load_rwku_data, prepare_tokenized_dataset, evaluate_model
from torch.utils.data import DataLoader
from datasets import load_dataset


DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {DEVICE}")

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: mps

In [2]:
MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"

SUBJECT   = "Donald Trump"

GRID = [
    {"lr": 1e-6, "retain_loss_weight": 1.0},
    {"lr": 1e-6, "retain_loss_weight": 5.0},
    {"lr": 1e-6, "retain_loss_weight": 10.0},
    {"lr": 5e-5, "retain_loss_weight": 1.0},
    {"lr": 5e-5, "retain_loss_weight": 5.0},
    {"lr": 5e-5, "retain_loss_weight": 10.0},
    {"lr": 2e-4, "retain_loss_weight": 1.0},
    {"lr": 2e-4, "retain_loss_weight": 5.0},
    {"lr": 2e-4, "retain_loss_weight": 10.0},
]

In [3]:
print(f"Loading model: {MODEL_ID}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype=torch.float16)
model = model.to(DEVICE)
model.eval()
print("Model ready")

Loading model: Qwen/Qwen2.5-3B-Instruct

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 434/434 [00:03<00:00, 111.11it/s]

Model ready

# base model score:

In [4]:
#load data

person_train, questions_forget, keywords_forget, questions_retain, keywords_retain = (
    load_rwku_data(SUBJECT)
)
tokenized_forget = prepare_tokenized_dataset(person_train, tokenizer)

retain_texts = [f"{q} {a}" for q, a in zip(questions_retain, keywords_retain)]
retain_raw   = HFDataset.from_dict({"text": retain_texts})
retain_raw   = retain_raw.map(lambda ex: {"text_formatted": ex["text"]})

def _tok(examples):
    return tokenizer(examples["text_formatted"],  padding="max_length",  truncation=True,   max_length=200,)

tokenized_retain = retain_raw.map(_tok, batched=True)
tokenized_retain = tokenized_retain.map(lambda x: {"labels": x["input_ids"]})
tokenized_retain.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
tokenized_forget.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

print("Starting Gradient Difference unlearning")

Questions for forgetting test: 20
Questions for general knowledge test: 30
Texts for training (unlearning): 226
Data is ready

Map: 100%|██████████| 30/30 [00:00<00:00, 15376.89 examples/s]
Map: 100%|██████████| 30/30 [00:00<00:00, 5740.64 examples/s]
Map: 100%|██████████| 30/30 [00:00<00:00, 6779.59 examples/s]

Starting Gradient Difference unlearning

In [5]:
print("\nBASELINE EFFICACY TEST (before unlearning)")
acc_forget_before = evaluate_model(model, tokenizer, questions_forget, keywords_forget, DEVICE)
print("\nBASELINE RETENTION TEST (before unlearning)")
acc_retain_before = evaluate_model(model, tokenizer, questions_retain, keywords_retain, DEVICE)

BASELINE EFFICACY TEST (before unlearning)
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that trump co-produced and hosted from 20'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice to fill in the blank in the given sentence, the correct answer is:

the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'samuel alito
the sentence would read: "during his presidency, donald trump appointed neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence should be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett kavanaugh
the sentence should read: "trump appointed brett kavanaugh, brett gorsuch, and amy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%

BASELINE RETENTION TEST (before unlearning)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016
the sentence implies that the election interference was conducted against the 20'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
in 2008, barack obama chose joe biden as his running mate.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence would be: "joe biden moved with his family to delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would read: "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
in the 2020 united states presidential election, joe biden ran with the junior'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '54th
the sentence "the 2020 united states presidential election was the'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 63.33%

In [6]:
class GradientDifferenceTrainer(Trainer):
    def __init__(self, *args, retain_dataset=None, retain_loss_weight: float = 1.0, **kwargs):
        super().__init__(*args, **kwargs)

        if retain_dataset is None:
            raise ValueError("provide retain_dataset")

        self.retain_loss_weight = retain_loss_weight

        self._retain_loader = DataLoader(
            retain_dataset,
            batch_size=self.args.per_device_train_batch_size,
            shuffle=True,
            collate_fn=self.data_collator,
        )
        self._retain_iter = iter(self._retain_loader)


    def _next_retain_batch(self):
        try:
            batch = next(self._retain_iter)
        except StopIteration:
            self._retain_iter = iter(self._retain_loader)
            batch = next(self._retain_iter)
        return batch

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        forget_outputs = model(**inputs)
        forget_loss    = forget_outputs.loss

        retain_batch = self._next_retain_batch()
        retain_batch = {k: v.to(model.device) for k, v in retain_batch.items()}
        retain_outputs = model(**retain_batch)
        retain_loss    = retain_outputs.loss

        # Negate forget_loss -> maximise it
        # Keep retain_loss positive -> minimise it
        gd_loss = -forget_loss + self.retain_loss_weight * retain_loss

        return (gd_loss, forget_outputs) if return_outputs else gd_loss

In [7]:
import csv

csv_path = "./unlearning_grid_results_Qwen2.5-3B.csv"
with open(csv_path, "w", newline="") as f:
    csv.DictWriter(f, fieldnames=[
        "model", "subject", "lr", "retain_loss_weight",
        "efficacy_before", "efficacy_after",
        "retain_before",   "retain_after",
    ]).writeheader()

for config in GRID:
    lr  = config["lr"]
    rlw = config["retain_loss_weight"]
    print(f"\n{'='*60}")
    print(f"Config: lr={lr}  retain_loss_weight={rlw}")
    print(f"{'='*60}")

    fresh_model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype=torch.float16).to(DEVICE)
    fresh_peft  = get_peft_model(fresh_model, LoraConfig(
        r=16, lora_alpha=32,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    ))

    trainer = GradientDifferenceTrainer(
        model=fresh_peft,
        args=TrainingArguments(
            output_dir=f"../gd_results_lr{lr}_rlw{rlw}",
            per_device_train_batch_size=1,
            gradient_accumulation_steps=2,
            learning_rate=lr,
            max_steps=100,
            logging_steps=5,
            optim="adamw_torch",
            remove_unused_columns=False,
            report_to="none",
        ),
        train_dataset=tokenized_forget,
        retain_dataset=tokenized_retain,
        retain_loss_weight=rlw,
    )

    print("Training")
    trainer.train()

    print("Evaluating after unlearning")
    eff_after = evaluate_model(fresh_peft, tokenizer, questions_forget, keywords_forget, DEVICE)
    ret_after = evaluate_model(fresh_peft, tokenizer, questions_retain, keywords_retain, DEVICE)

    print(f"Efficacy:  {acc_forget_before:.2f}% -> {eff_after:.2f}%  (lower is better)")
    print(f"Retention: {acc_retain_before:.2f}% -> {ret_after:.2f}%  (higher is better)")

    with open(csv_path, "a", newline="") as f:
        csv.DictWriter(f, fieldnames=[
            "model", "subject", "lr", "retain_loss_weight",
            "efficacy_before", "efficacy_after",
            "retain_before",   "retain_after",
        ]).writerow({
            "model": MODEL_ID, "subject": SUBJECT,
            "lr": lr, "retain_loss_weight": rlw,
            "efficacy_before": f"{acc_forget_before:.2f}",
            "efficacy_after":  f"{eff_after:.2f}",
            "retain_before":   f"{acc_retain_before:.2f}",
            "retain_after":    f"{ret_after:.2f}",
        })

    del fresh_model, fresh_peft, trainer
    if DEVICE == "mps":
        torch.mps.empty_cache()

print(f"Results saved to {csv_path}")

============================================================
Config: lr=1e-06  retain_loss_weight=1.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:05<00:00, 74.74it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that trump co-produced and hosted from 20'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice to fill in the blank in the given sentence, the correct answer is:

the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'samuel alito
the sentence would read: "during his presidency, donald trump appointed neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence should be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett kavanaugh
the sentence should read: "trump appointed brett kavanaugh, brett gorsuch, and amy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016
the sentence implies that the election interference was conducted against the 20'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
in 2008, barack obama chose joe biden as his running mate.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence would be: "joe biden moved with his family to delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would read: "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
in the 2020 united states presidential election, joe biden ran with the junior'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '54th
the sentence "the 2020 united states presidential election was the'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 63.33%
Efficacy:  85.00% -> 85.00%  (lower is better)
Retention: 63.33% -> 63.33%  (higher is better)

============================================================
Config: lr=1e-06  retain_loss_weight=5.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:02<00:00, 148.24it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that trump co-produced and hosted from 20'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice to fill in the blank in the given sentence, the correct answer is:

the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'samuel alito
the sentence would read: "during his presidency, donald trump appointed neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence should be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett kavanaugh
the sentence should read: "trump appointed brett kavanaugh, brett gorsuch, and amy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016
the sentence implies that the election interference was conducted against the 20'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
in 2008, barack obama chose joe biden as his running mate.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence would be: "joe biden moved with his family to delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would read: "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
in the 2020 united states presidential election, joe biden ran with the junior'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '54th
the sentence "the 2020 united states presidential election was the'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 63.33%
Efficacy:  85.00% -> 85.00%  (lower is better)
Retention: 63.33% -> 63.33%  (higher is better)

============================================================
Config: lr=1e-06  retain_loss_weight=10.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:03<00:00, 143.69it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that trump co-produced and hosted from 20'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice to fill in the blank in the given sentence, the correct answer is:

the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'samuel alito
the sentence would read: "during his presidency, donald trump appointed neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence should be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett kavanaugh
the sentence should read: "trump appointed brett kavanaugh, brett gorsuch, and amy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016
the sentence implies that the election interference was conducted against the 20'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
in 2008, barack obama chose joe biden as his running mate.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be completed as: "joe biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be completed as: "joe biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence would be: "joe biden moved with his family to delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be completed as: "joe biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would read: "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be completed as: "joe biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
the sentence would be completed as: "in the 2020 united states presidential'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '54th
the sentence "the 2020 united states presidential election was the'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 63.33%
Efficacy:  85.00% -> 85.00%  (lower is better)
Retention: 63.33% -> 63.33%  (higher is better)

============================================================
Config: lr=5e-05  retain_loss_weight=1.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:01<00:00, 274.47it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that aired from 2004 to'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
the sentence would be completed as: donald john trump was born on june 2'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice to fill in the blank in the given sentence, the correct answer is:

the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
the sentence would be completed as: "a special counsel investigation established that russians had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence would be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
the sentence would be completed as: "a special counsel investigation established that russians had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett
the sentence should read: "trump appointed brett gorsuch, brett kavanaugh, and amy c'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden
the sentence would be completed as: "trump refused to concede after losing the 20'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 90.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the sentence would read: "the list of individuals and organizations is related to either the election'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
the sentence would be completed as: "in 2008, barack obama'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the answer is:

kamala

the sentence should read:'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be completed as: "biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence "joe biden moved with his family to delaware in ___"'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be completed as: "biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the answer is:

kamala

the sentence should read:'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would read: "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows: "the january 6, 202'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
the sentence would be completed as: "in the 2020 united states presidential'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california
the sentence would read: "during the 2020 united states presidential election,'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '7th
the sentence "the 2020 united states presidential election was the ___'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 60.00%
Efficacy:  85.00% -> 90.00%  (lower is better)
Retention: 63.33% -> 60.00%  (higher is better)

============================================================
Config: lr=5e-05  retain_loss_weight=5.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:02<00:00, 182.64it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump hosted from 2004'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
the sentence would be completed as: "a special counsel investigation established that russians had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence would be completed as: "trump won the 2016 presidential election'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
the sentence would be completed as: "a special counsel investigation established that russians had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett
the sentence should read: "trump appointed brett gorsuch, brett kavanaugh, and amy c'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden
the sentence would be completed as: "trump refused to concede after losing the 20'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would be completed as: "in 2021'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 90.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the sentence would read: "the list of individuals and organizations is related to either the election'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
the sentence would be completed as: "in 2008, barack obama'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the answer is:

kamala

the sentence should read:'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "biden earned his law degree from ___ university" could be completed with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence "joe biden moved with his family to delaware in ___"'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "biden earned his law degree from ___ university" could be completed with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the answer is:

kamala

the sentence should read:'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence likely continues as "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

"the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
the sentence would be completed as: "in the 2020 united states presidential'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california
the sentence would read: "during the 2020 united states presidential election,'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '7th
the sentence "the 2020 united states presidential election was the ___'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 60.00%
Efficacy:  85.00% -> 90.00%  (lower is better)
Retention: 63.33% -> 60.00%  (higher is better)

============================================================
Config: lr=5e-05  retain_loss_weight=10.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:02<00:00, 210.32it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump co-produced and hosted from 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the apprentice was a reality television series that donald trump hosted from 2004'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
the sentence would be completed as: "a special counsel investigation established that russians had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence would be completed as: "trump won the 2016 presidential election'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
the sentence would be completed as: "a special counsel investigation established that russians had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett
the sentence should read: "trump appointed brett gorsuch, brett kavanaugh, and amy c'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden
the sentence would be completed as: "trump refused to concede after losing the 20'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would be completed as: "in 2021'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 90.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the sentence would read: "the list of individuals and organizations is related to either the election'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
the sentence would be completed as: "in 2008, barack obama'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the answer is:

kamala

the sentence should read:'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "biden earned his law degree from ___ university" could be completed with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence "joe biden moved with his family to delaware in ___"'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "biden earned his law degree from ___ university" could be completed with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the answer is:

kamala

the sentence should read:'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence likely continues as "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence "joe biden earned his law degree from ___ university" is often filled with "'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

"the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
the sentence would be completed as: "in the 2020 united states presidential'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
you are correct. the sentence should read:

"in the 2020 united'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california
the sentence would be completed as: during the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '7th
the sentence "the 2020 united states presidential election was the ___'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 60.00%
Efficacy:  85.00% -> 90.00%  (lower is better)
Retention: 63.33% -> 60.00%  (higher is better)

============================================================
Config: lr=0.0002  retain_loss_weight=1.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:03<00:00, 114.09it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '41'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'celebrity apprentice
answer: celebrity apprentice'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '41'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'celebrity apprentice
answer: celebrity apprentice'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'celebrity apprentice
answer: celebrity apprentice'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '12'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'reality
answer: reality'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
answer: russians'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'justice'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
answer: russians'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'sonia_christina_curzio'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'to'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 50.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'answer: answer:'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'mccain'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ᵘ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'childhood'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ᵘ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ̣̪̱͈̤̀̑̑̅'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
answer: 5'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ ᵗ ᵖ ᵘ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ ᵗ ᵖ ᵘ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
answer: november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamală
answer: kamală'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '8th'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 36.67%
Efficacy:  85.00% -> 50.00%  (lower is better)
Retention: 63.33% -> 36.67%  (higher is better)

============================================================
Config: lr=0.0002  retain_loss_weight=5.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:04<00:00, 93.31it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
answer: 45th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice
answer:the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
answer: 45th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice
answer:the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '14th
answer: 14th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice
answer:the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary
answer: hillary

answer: hillary

answer: hillary

answer: hillary

answer:'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary
answer: hillary

answer: hillary

answer: hillary

answer: hillary

answer:'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
answer: russians'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: '__samuel alito__'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican

the sentence would be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians
answer: russians'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy_clauset
note: this is a placeholder name that does not correspond to any actual person'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary
answer: hillary

answer: hillary

answer: hillary

answer: hillary

answer:'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
answer: muslim'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: '___trump appointed brett gorsuch, kavanaugh, and amy coney barrett to the u.s. supreme'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would be: "in what year did trump urge his supporters'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 90.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia

the timeline of russian interference in the 2016 united states elections involves events related'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the list of relevant individuals and organizations is related to events concerning the election interference that russia conducted'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware

the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama

the sentence is "in 2008, barack obama chose joe biden as'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale
answer: yale'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
answer: kamala'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware

the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale
answer: yale'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale
answer: yale'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
answer: senate'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale
answer: yale'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale
answer: yale'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
answer: kamala'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware

the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
answer: delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale
answer: yale'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the united states capitol building was attacked on january 5, 2021'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
answer: trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: '11th
answer: 11th'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
answer: kamala'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california
answer: california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '5th'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 46.67%
Efficacy:  85.00% -> 90.00%  (lower is better)
Retention: 63.33% -> 46.67%  (higher is better)

============================================================
Config: lr=0.0002  retain_loss_weight=10.0
============================================================

Loading weights: 100%|██████████| 434/434 [00:01<00:00, 228.64it/s]

Training

/Users/user/Desktop/school/master's <3/semester III/Machine-Unlearning-for-llms/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Evaluating after unlearning
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
answer: 45th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice
answer: the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
answer: 45th'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
answer: the apprentice'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice
answer: the apprentice'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '01
answer: 01'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice
answer:the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary
answer: hillary

answer: hillary

answer: hillary

answer: hillary

answer:'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary
answer: hillary

answer: hillary

answer: hillary

answer: hillary

answer:'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians

the sentence should read: "a special counsel investigation established that russians had interfered in the'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: '__samuel alito__answer: __samuel alito__answer: __samuel al'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican

the sentence would be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russians

the sentence should read: "a special counsel investigation established that russians had interfered in the'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy_clauset'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary
answer: hillary

answer: hillary

answer: hillary

answer: hillary

answer:'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
answer: muslim'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: '___trump appointed brett gorsuch, kavanaugh, and amy coney barrett to the u.s. supreme'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
___
2021
in what year did trump urge his'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia

the timeline of russian interference in the 2016 united states elections involves events related'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic
the list of relevant individuals and organizations is related to events concerning the election interference that russia conducted'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'democratic'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware

the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama

the sentence would be: "in 2008, barack obama chose joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: '___vanderbilt'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
answer: kamala'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware

the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale

the sentence would be completed as "biden earned his law degree from yale university." however'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: '___vanderbilt'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
answer: senate'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'yale

the sentence would be completed as "biden earned his law degree from yale university." however'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: '___vanderbilt'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
answer: kamala'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware

the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: '___vanderbilt'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒ'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the united states capitol building was attacked on january 5, 2021'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒepy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump

the sentence is completed as follows:

"on january 6, 2021,'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ᵒepy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
answer: november'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on tuesday. task: fill'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
answer: kamala'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on tuesday. task: fill'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '5th'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 50.00%
Efficacy:  85.00% -> 85.00%  (lower is better)
Retention: 63.33% -> 50.00%  (higher is better)
Results saved to ./unlearning_grid_results_Qwen2.5-3B.csv