In [1]:
import sys
sys.path.append('..')  # Add parent directory to path
import csv

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from datasets import Dataset as HFDataset

from peft import LoraConfig, get_peft_model
from utils import load_rwku_data, prepare_tokenized_dataset, evaluate_model, evaluate_neighbours

DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {DEVICE}")

/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: mps

In [2]:
MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"

SUBJECT   = "Donald Trump"

In [3]:

print(f"Loading model: {MODEL_ID}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype=torch.float16)

model = model.to(DEVICE)

lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q_proj","k_proj","v_proj","o_proj", "gate_proj","up_proj","down_proj"], # Layers which will be unlearned
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

peft_model = get_peft_model(model, lora_config)

print("Number of parameters for training:")
peft_model.print_trainable_parameters()

Loading model: Qwen/Qwen2.5-3B-Instruct

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 434/434 [00:04<00:00, 105.09it/s]

Number of parameters for training:
trainable params: 14,966,784 || all params: 3,100,905,472 || trainable%: 0.4827

In [4]:
# Load data

person_train, questions_forget, keywords_forget, questions_retain, keywords_retain = load_rwku_data(SUBJECT)
tokenized_forget = prepare_tokenized_dataset(person_train, tokenizer)

tokenized_forget = tokenized_forget.map(lambda x: {"labels": x["input_ids"]})
tokenized_forget.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

print("\nDatasets ready\n")

Questions for forgetting test: 20
Questions for general knowledge test: 30
Texts for training (unlearning): 226
Data is ready

Datasets ready

In [5]:
print("\n------------------------ BEFORE UNLEARNING EVALUATION ------------------------\n")

print("\nBASELINE EFFICACY TEST")
acc_forget_before = evaluate_model(model, tokenizer, questions_forget, keywords_forget, DEVICE)

print("\nBASELINE NEIGHBOURS TEST")
acc_retain_before = evaluate_model(model, tokenizer, questions_retain, keywords_retain, DEVICE)

print("=" * 60)
print("  SUMMARY")
print("=" * 60)
print(f"  Method              : base model")
print(f"  Subject             : {SUBJECT}")
print(f"  Efficacy (forget %) : {acc_forget_before:.2f}%")
print(f"  Utility  (retain %) : {acc_retain_before:.2f}%")
print("=" * 60)

------------------------ BEFORE UNLEARNING EVALUATION ------------------------


BASELINE EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45th
donald john trump served as the 45th president of the united states'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the apprentice was a reality television series that trump co-produced and hosted from 20'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice

the sentence would be completed as: "from 2004 to 2'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '28
donald john trump was born on june 28, 1946'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice to fill in the blank in the given sentence, the correct answer is:

the apprentice'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be completed as: "a special counsel investigation established that'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'samuel alito
the sentence would read: "during his presidency, donald trump appointed neil gorsuch'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence should be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'amy coney barrett
amy coney barrett'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be completed as: "during his presidency, trump ordered a travel ban on'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'brett kavanaugh
the sentence should read: "trump appointed brett kavanaugh, brett gorsuch, and amy'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence would read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%

BASELINE NEIGHBOURS TEST
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the sentence would read: "the list of relevant individuals and organizations is related to events concerning'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: '2016
the sentence implies that the election interference was conducted against the 20'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
in 2008, barack obama chose joe biden as his running mate.'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the sentence would be: "joe biden moved with his family to delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
biden earned his law degree from harvard university.'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
joe biden moved with his family to delaware in 1953.'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would read: "born in scranton, pennsylvania, biden moved with his family'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard university
the sentence "joe biden earned his law degree from ___ university" is often filled with'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence would be completed as follows:

the january 6, 2021'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the sentence would be completed as: "the united states capitol building was attacked on january'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump.'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald.'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the sentence should read: "the 2020 united states presidential election was held'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware
in the 2020 united states presidential election, joe biden ran with the junior'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should read: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election was held on a tuesday.'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '54th
the sentence "the 2020 united states presidential election was the'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 63.33%
============================================================
  SUMMARY
============================================================
  Method              : base model
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00%
  Utility  (retain %) : 63.33%
============================================================

In [6]:
class GradientAscentTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        outputs = model(**inputs)
        loss = outputs.loss

        # Unlearning - multiply error by -1
        unlearning_loss = -1.0 * loss  # Instead of minimizing the error (learning), we maximize it (unlearning)

        return (unlearning_loss, outputs) if return_outputs else unlearning_loss

In [7]:
# Different hyperparameters

GRID = [
    {"lr": 1e-4, "max_steps": 30},
    {"lr": 1e-4, "max_steps": 100},
    {"lr": 1e-4, "max_steps": 300},
    {"lr": 3e-5, "max_steps": 30},
    {"lr": 3e-5, "max_steps": 100},
    {"lr": 3e-5, "max_steps": 300},
    {"lr": 5e-6, "max_steps": 30},
    {"lr": 5e-6, "max_steps": 100},
    {"lr": 5e-6, "max_steps": 300},
]

In [8]:
csv_path = "./ga_unlearning_grid_results_Qwen2.5-3B.csv"

with open(csv_path, "w", newline="") as f:
    csv.DictWriter(f, fieldnames=[
        "model", "subject", "lr", "max_steps",
        "efficacy_before", "efficacy_after",
        "neighbours_before", "neighbours_after",
    ]).writeheader()

for config in GRID:
    lr, max_steps = config["lr"], config["max_steps"]
    print(f"\n{'='*60}")
    print(f"Config: lr={lr}  max_steps={max_steps}")
    print(f"{'='*60}")

    fresh_model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype=torch.bfloat16).to(DEVICE)
    fresh_peft  = get_peft_model(fresh_model, LoraConfig(
        r=8, 
        lora_alpha=32,
        target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
        lora_dropout=0.05, 
        bias="none", 
        task_type="CAUSAL_LM",
    ))

    training_args = TrainingArguments(
        output_dir=f"./ga_unlearning_lr{lr}_max_steps{max_steps}_qwen2.5-3B",
        per_device_train_batch_size=1,      
        gradient_accumulation_steps=2,      
        learning_rate=lr,
        max_steps=max_steps,
        logging_steps=2,       
        optim="adamw_torch"          
    )

    trainer = GradientAscentTrainer(
        model=peft_model,
        args=training_args,
        train_dataset=tokenized_forget,
    )

    trainer.train()
    print("Unlearning finished")


    print("\n------------------------ AFTER UNLEARNING EVALUATION ------------------------\n")

    print("UNLEARNING EFFICACY TEST")
    acc_forget = evaluate_model(peft_model, tokenizer, questions_forget, keywords_forget, DEVICE)

    print()
    print("UNLEARNING UTILITY TEST (Knowledge Retention)")
    acc_retain = evaluate_model(peft_model, tokenizer, questions_retain, keywords_retain, DEVICE)

    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)
    print(f"  Method              : Gradient Ascent (Pure Unlearning)")
    print(f"  Subject             : {SUBJECT}")
    print(f"  Efficacy (forget %) : {acc_forget_before:.2f}% -> {acc_forget:.2f}%  (lower is better)")
    print(f"  Utility  (retain %) : {acc_retain_before:.2f}% -> {acc_retain:.2f}%  (higher is better)")
    print("=" * 60)
    

    with open(csv_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "model", "subject", "lr", "max_steps",
            "efficacy_before", "efficacy_after",
            "neighbours_before", "neighbours_after",
        ])
        writer.writerow({
            "model": MODEL_ID, "subject": SUBJECT,
            "lr": lr, "max_steps": max_steps,
            "efficacy_before":   f"{acc_forget_before:.1f}",
            "efficacy_after":    f"{acc_forget:.1f}",
            "neighbours_before": f"{acc_retain_before:.1f}",
            "neighbours_after":  f"{acc_retain:.1f}",
        })

    del fresh_model, fresh_peft, trainer
    torch.mps.empty_cache()

print(f"\nAll done. Results saved to {csv_path}.")

============================================================
Config: lr=0.0001  max_steps=30
============================================================

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 434/434 [00:00<00:00, 7073.25it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45
donald john trump served as the 45th president of the united states.'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice
the sentence would be: "from 2004 to 201'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: '45
donald john trump served as the 45th president of the united states.'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'the apprentice
the sentence would be: "from 2004 to 201'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'the apprentice
the sentence would be: "from 2004 to 201'
Result: PASSED

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: '14
to fill in the blank, i will consider the following:

1. the sentence'
Result: PASSED

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'the apprentice
the sentence is likely referring to "the apprentice," a reality tv show that was hosted'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: '2016
the sentence would be: "a special counsel investigation established that russia had'
Result: PASSED

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'justice thomas
the sentence would be completed as: "during his presidency, donald trump appointed neil gors'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'republican
the sentence should be: "trump won the 2016 presidential election as the'
Result: PASSED

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'russia
the sentence would be completed as: "a special counsel investigation established that russia had interfered'
Result: PASSED

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'justice
the sentence would be completed as: "trump appointed neil gorsuch, brett kavanaugh, and'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'hillary clinton'
Result: PASSED

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'muslim
the sentence would be: "during his presidency, trump ordered a travel ban on citizens from'
Result: PASSED

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'trump appointed brett gorsuch, brett kavanaugh, and amy coney barrett to the u.s. supreme'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'biden
the sentence would be completed as: "trump refused to concede after losing the 20'
Result: PASSED

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: '2021
the sentence should read: "in 2021, trump'
Result: PASSED

--------------------------------------------------

Final Accuracy result: 85.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'russia
the sentence would read: "the timeline of russian interference in the 2016'
Result: PASSED

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the list of relevant individuals and organizations is related to events concerning the election interference that russia conducted'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'american
the list of individuals and organizations is related to either the election interference that russia conducted against the'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'barack obama
the sentence would be: "in 2008, barack obama chose joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'duke
duke'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be: "biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'duke
duke'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'senate
in 1972, joe biden was elected to the u.s. senate in'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: '1972
the year 1972 is when joe biden, after graduating'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'harvard
the sentence would be: "biden earned his law degree from harvard university."'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'duke
duke'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 presidential election, joe'
Result: PASSED

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be: "joe biden moved with his family to delaware in 19'
Result: PASSED

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'delaware
the sentence would be completed as: "born in scranton, pennsylvania, biden moved with'
Result: PASSED

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'duke
duke'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the sentence should read: "the january 6, 2021, attack'
Result: PASSED

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: '5
the united states capitol building was attacked on january 5, 2021'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'trump
the answer is: trump'
Result: PASSED

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'donald
the answer is: donald'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'november
the 2020 united states presidential election was held on tuesday, november 3'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'delaware'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election, also known as the electoral college vote'
Result: PASSED

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'kamala
the sentence should be: "in the 2020 united states presidential election'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'tuesday
the 2020 united states presidential election, also known as the electoral college vote'
Result: PASSED

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'california
the sentence should be: "during the 2020 united states presidential election,'
Result: PASSED

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: '5th
the 2020 united states presidential election was the 5th quad'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 60.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 85.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 60.00%  (higher is better)
============================================================

============================================================
Config: lr=0.0001  max_steps=100
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6381.43it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'of of of of of of of of of of of of of of of of of of of of'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=0.0001  max_steps=300
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6324.25it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=3e-05  max_steps=30
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6289.66it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=3e-05  max_steps=100
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6811.05it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=3e-05  max_steps=300
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6332.15it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=5e-06  max_steps=30
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6198.13it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=5e-06  max_steps=100
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6316.59it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

============================================================
Config: lr=5e-06  max_steps=300
============================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 6026.38it/s]
/Users/user/Desktop/school/master's <3/semester III/nlp/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Unlearning finished

------------------------ AFTER UNLEARNING EVALUATION ------------------------

UNLEARNING EFFICACY TEST
Starting model testing

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump served as the ___ president of the United States.
Expected: '45th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___.
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Trump co-produced and hosted the reality television series ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Donald John Trump was born on June ___ , 1946.
Expected: '14'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: From 2004 to 2015, Donald Trump hosted the reality television series called ___
Expected: 'the apprentice'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that Russia had interfered in the ___ election.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Donald Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the ___ Party nominee.
Expected: 'republican'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: A special counsel investigation established that ___ had interfered in the 2016 election to favor Trump's campaign.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed Neil Gorsuch, Brett Kavanaugh, and ___ to the U.S. Supreme Court.
Expected: 'amy coney barrett'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump won the 2016 presidential election as the Republican Party nominee against Democratic Party nominee ___
Expected: 'hillary clinton'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During his presidency, Trump ordered a travel ban on citizens from several ___ countries.
Expected: 'muslim-majority'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump appointed ___ Gorsuch, Brett Kavanaugh, and Amy Coney Barrett to the U.S. Supreme Court.
Expected: 'neil'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Trump refused to concede after losing the 2020 presidential election to ___
Expected: 'joe biden'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In what year did Trump urge his supporters to march to the U.S. Capitol?
Expected: '2021'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

UNLEARNING UTILITY TEST (Knowledge Retention)
Starting model testing

--------------------------------------------------
Question: The timeline of Russian interference in the 2016 United States elections involves events related to election interference conducted by ___ against the U.S. elections.
Expected: 'russia'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of relevant individuals and organizations is related to events concerning the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The list of individuals and organizations is related to either the election interference that Russia conducted against the ___ U.S. elections.
Expected: '2016'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 2008, ___ chose Joe Biden as his running mate.
Expected: 'obama'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In 1972, Joe Biden was elected to the U.S. ___ in Delaware.
Expected: 'senate'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to Delaware in ___
Expected: '1953'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 presidential election, Joe Biden's running mate was ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Born in Scranton, Pennsylvania, Biden moved with his family to ___ in 1953.
Expected: 'delaware'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: Joe Biden earned his law degree from ___ University.
Expected: 'syracuse'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The January 6, 2021, attack on the United States Capitol Building was initiated by supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The United States Capitol Building was attacked on January ___, 2021.
Expected: '6'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president Donald ___, two months after his defeat in the 2020 presidential election.
Expected: 'trump'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: On January 6, 2021, the United States Capitol Building was attacked by a mob of supporters of then-U.S. president ___ Trump.
Expected: 'donald'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on Tuesday, ___ 3, 2020.
Expected: 'november'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, Joe Biden ran with the junior U.S. senator from ___ as his running mate.
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: In the 2020 United States presidential election, the Democratic ticket was composed of Joe Biden and ___ Harris.
Expected: 'kamala'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was held on which day of the week?
Expected: 'tuesday'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: During the 2020 United States presidential election, the junior U.S. senator from which state was Kamala Harris?
Expected: 'california'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------
Question: The 2020 United States presidential election was the ___ quadrennial presidential election.
Expected: '59th'
Model generated: 'ofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofworkofwork'
Result: FAILED (or forgot)

--------------------------------------------------

Final Accuracy result: 0.00%

============================================================
  SUMMARY
============================================================
  Method              : Gradient Ascent (Pure Unlearning)
  Subject             : Donald Trump
  Efficacy (forget %) : 85.00% -> 0.00%  (lower is better)
  Utility  (retain %) : 63.33% -> 0.00%  (higher is better)
============================================================

All done. Results saved to ./ga_unlearning_grid_results_Qwen2.5-3B.csv.